#lang sicp

(define *table* '())

(define (put op type item)
  (set! *table* (cons (list op type item) *table*)))
(define (get op type)
  (define (lookup key table)
    (cond ((null? table) #f)
          ((and (equal? (caar table) op)
                (equal? (cadar table) type))
           (caddar table))
          (else (lookup key (cdr table)))))
  (lookup (list op type) *table*))

(define (attach-tag type-tag contents)
  (cons type-tag contents))
(define (type-tag datum)
  (if (pair? datum)
      (car datum)
      (error "bad tagged datum: TYPE-TAG" datum)))
(define (contents datum)
  (if (pair? datum)
      (cdr datum)
      (error "bad tagged datum: CONTENTS" datum)))

(define (square x) (* x x))

(define (apply-generic op . args)
  (define (raise-to-top obj raised-objs)
    (let ((type (type-tag obj)))
      (let ((raise-proc (get 'raise (list type))))
        (if raise-proc
            (let ((raised-obj (raise obj)))
              (raise-to-top raised-obj
                            (append raised-objs (list raised-obj))))
            raised-objs))))
  (define (raise-to-level raise-path level)
    (if (= level 0)
        (car raise-path)
        (raise-to-level (cdr raise-path) (- level 1))))
  (define (coerce obj1 obj2)
    (let ((raise-path-1 (raise-to-top obj1 (list obj1)))
          (raise-path-2 (raise-to-top obj2 (list obj2))))
      (let ((raise-length-1 (length raise-path-1))
            (raise-length-2 (length raise-path-2)))
        (let ((delta (- raise-length-1 raise-length-2)))
          (cond ((= delta 0)
                 (list obj1 obj2))
                ((< delta 0)
                 (list obj1
                       (raise-to-level raise-path-2
                                       (abs delta))))
                (else (list (raise-to-level raise-path-1 delta)
                            obj2)))))))
  (let ((type-tags (map type-tag args)))
    (let ((proc (get op type-tags)))
      (if proc
          (apply proc (map contents args))
          (if (= (length args) 2)
              (let ((obj1 (car args))
                    (obj2 (cadr args)))
                (let ((coerced-objs (coerce obj1 obj2)))
                  (let ((c-obj1 (car coerced-objs))
                        (c-obj2 (cadr coerced-objs)))
                    (if (eq? (type-tag c-obj1)
                             (type-tag c-obj2))
                        (apply-generic op c-obj1 c-obj2)
                        (error "Objects do not exist in the same tower hierarchy of types: APPLY-GENERIC"
                               (list op type-tags))))))
              (error "No method for these types: APPLY-GENERIC"
                     (list op type-tags)))))))

(define (install-integer-package)
  (define (make-integer n) (floor n))
  (define (tag n) (attach-tag 'integer n))
  (define (integer->rational n)
    (make-rational n 1))
  (put 'make 'integer
       (lambda (x) (tag (make-integer x))))
  (put 'add '(integer integer)
       (lambda (x y) (tag (+ x y))))
  (put 'raise '(integer) integer->rational)
  'done)
(define (make-integer n)
  ((get 'make 'integer) n))

(define (install-rational-package)
  (define (numer x) (car x))
  (define (denom x) (cdr x))
  (define (make-rat n d)
    (let ((g (gcd n d)))
      (cons (/ n g) (/ d g))))
  (define (add-rat x y)
    (make-rat (+ (* (numer x) (denom y))
                 (* (numer y) (denom x)))
              (* (denom x) (denom y))))
  (define (tag x) (attach-tag 'rational x))
  (define (rational->real x)
    (make-real (/ (numer x) (denom x))))
  (put 'make 'rational
    (lambda (n d) (tag (make-rat n d))))
  (put 'add '(rational rational)
       (lambda (x y) (tag (add-rat x y))))
  (put 'raise '(rational) rational->real)
  'done)
(define (make-rational n d)
  ((get 'make 'rational) n d))

(define (install-real-package)
  (define (make-real x) (/ x 1.0))
  (define (tag n) (attach-tag 'real n))
  (define (real->complex n)
    (make-complex-from-real-imag n 0))
  (put 'make 'real
       (lambda (x) (tag (make-real x))))
  (put 'add '(real real)
       (lambda (x y) (tag (+ x y))))
  (put 'raise '(real) real->complex)
  'done)
(define (make-real n)
  ((get 'make 'real) n))

(define (install-polar-package)
  (define (real-part z)
    (* (magnitude z) (cos (angle z))))
  (define (imag-part z)
    (* (magnitude z) (sin (angle z))))
  (define (magnitude z) (car z))
  (define (angle z) (cdr z))
  (define (make-from-mag-ang r a) (cons r a))
  (define (make-from-real-imag x y)
    (cons (sqrt (+ (square x) (square y)))
          (atan y x)))
  (define (tag z) (attach-tag 'polar z))
  (put 'real-part '(polar) real-part)
  (put 'imag-part '(polar) imag-part)
  (put 'magnitude '(polar) magnitude)
  (put 'angle '(polar) angle)
  (put 'make-from-mag-ang 'polar
       (lambda (r a) (tag (make-from-mag-ang r a))))
  (put 'make-from-real-imag 'polar
       (lambda (x y) (tag (make-from-real-imag x y))))
  'done)

(define (install-rectangular-package)
  (define (real-part z) (car z))
  (define (imag-part z) (cdr z))
  (define (magnitude z)
    (sqrt (+ (square (real-part z))
             (square (imag-part z)))))
  (define (angle z)
    (atan (imag-part z) (real-part z)))
  (define (make-from-real-imag x y) (cons x y))
  (define (make-from-mag-ang r a)
    (cons (* r (cos a))
          (* r (sin a))))
  (define (tag z) (attach-tag 'rectangular z))
  (put 'real-part '(rectangular) real-part)
  (put 'imag-part '(rectangular) imag-part)
  (put 'magnitude '(rectangular) magnitude)
  (put 'angle '(rectangular) angle)
  (put 'make-from-mag-ang 'rectangular
       (lambda (r a) (tag (make-from-mag-ang r a))))
  (put 'make-from-real-imag 'rectangular
       (lambda (x y) (tag (make-from-real-imag x y))))
  'done)

(define (real-part z) (apply-generic 'real-part z))
(define (imag-part z) (apply-generic 'imag-part z))
(define (magnitude z) (apply-generic 'magnitude z))
(define (angle z) (apply-generic 'angle z))
(define (make-from-real-imag x y)
  ((get 'make-from-real-imag 'rectangular) x y))
(define (make-from-mag-ang r a)
  ((get 'make-from-mag-ang 'polar) r a))

(define (install-complex-package)
  (define (make-from-real-imag x y)
    ((get 'make-from-real-imag 'rectangular) x y))
  (define (make-from-mag-ang r a)
    ((get 'make-from-mag-ang 'polar) r a))
  (define (add-complex z1 z2)
    (make-from-real-imag (+ (real-part z1) (real-part z2))
                         (+ (imag-part z1) (imag-part z2))))
  (define (tag z) (attach-tag 'complex z))
  (put 'make-from-real-imag 'complex
       (lambda (x y) (tag (make-from-real-imag x y))))
  (put 'make-from-mag-ang 'complex
       (lambda (r a) (tag (make-from-mag-ang r a))))
  (put 'add '(complex complex)
       (lambda (z1 z2) (tag (add-complex z1 z2))))
  (put 'real-part '(complex) real-part)
  (put 'imag-part '(complex) imag-part)
  (put 'magnitude '(complex) magnitude)
  (put 'angle '(complex) angle)
  'done)
(define (make-complex-from-real-imag x y)
  ((get 'make-from-real-imag 'complex) x y))
(define (make-complex-from-mag-ang r a)
  ((get 'make-from-mag-ang 'complex) r a))

(define (raise obj)
  (apply-generic 'raise obj))
(define (add x y)
  (apply-generic 'add x y))

(install-integer-package)
(install-rational-package)
(install-real-package)
(install-polar-package)
(install-rectangular-package)
(install-complex-package)

; test: same types
(add (make-integer 3) (make-integer 5))
; test: integer + rational (raise integer)
(add (make-integer 2) (make-rational 1 3))
; test: integer + real (raise integer twice)
(add (make-integer 5) (make-real 2.5))
; test: integer + complex (raise integer three times)
(add (make-integer 1) (make-complex-from-real-imag 3 4))
; test: real + rational
(add (make-real 1.5) (make-rational 1 2))
