#lang sicp

(define *table* '())

(define (put op type item)
  (set! *table* (cons (list op type item) *table*)))
(define (get op type)
  (define (lookup key table)
    (cond ((null? table) #f)
          ((and (equal? (caar table) op)
                (equal? (cadar table) type))
           (caddar table))
          (else (lookup key (cdr table)))))
  (lookup (list op type) *table*))

(define (attach-tag type-tag contents)
  (if (eq? type-tag 'integer)
      contents
      (cons type-tag contents)))
(define (type-tag datum)
  (cond ((pair? datum) (car datum))
        ((number? datum) 'integer)
        (else (error "bad tagged datum: TYPE-TAG" datum))))
(define (contents datum)
  (cond ((pair? datum) (cdr datum))
        ((number? datum) datum)
        (else (error "bad tagged datum: CONTENTS" datum))))
(define (drop obj)
  (let ((project-proc (get 'project (list (type-tag obj)))))
    (if project-proc
        (let ((dropped-obj (project obj)))
          (let ((raise-proc (get 'raise (list (type-tag dropped-obj)))))
            (if (and raise-proc
                     (eq? (type-tag (raise dropped-obj)) (type-tag obj))
                     (equ? (raise dropped-obj) obj))
                (drop dropped-obj)
                obj)))
        obj)))
(define (apply-generic op . args)
  (define (raise-to-top obj raised-objs)
    (let ((type (type-tag obj)))
      (let ((raise-proc (get 'raise (list type))))
        (if raise-proc
            (let ((raised-obj (raise obj)))
              (raise-to-top raised-obj
                            (append raised-objs (list raised-obj))))
            raised-objs))))
  (define (raise-to-level raise-path level)
    (if (= level 0)
        (car raise-path)
        (raise-to-level (cdr raise-path) (- level 1))))
  (define (coerce obj1 obj2)
    (let ((raise-path-1 (raise-to-top obj1 (list obj1)))
          (raise-path-2 (raise-to-top obj2 (list obj2))))
      (let ((raise-length-1 (length raise-path-1))
            (raise-length-2 (length raise-path-2)))
        (let ((delta (- raise-length-1 raise-length-2)))
          (cond ((= delta 0)
                 (list obj1 obj2))
                ((< delta 0)
                 (list obj1
                       (raise-to-level raise-path-2
                                       (abs delta))))
                (else (list (raise-to-level raise-path-1 delta)
                            obj2)))))))
  (let ((type-tags (map type-tag args)))
    (let ((proc (get op type-tags)))
      (if proc
          (let ((result (apply proc (map contents args))))
            result)
          (if (= (length args) 2)
              (let ((obj1 (car args))
                    (obj2 (cadr args)))
                (cond ((eq? (type-tag obj1) 'polynomial)
                       (apply-generic
                        op obj1 (coerce-polynomial obj2 obj1)))
                      ((eq? (type-tag obj2) 'polynomial)
                       (apply-generic
                        op (coerce-polynomial obj1 obj2) obj2))
                      (else
                       (let ((coerced-objs (coerce obj1 obj2)))
                         (let ((c-obj1 (car coerced-objs))
                               (c-obj2 (cadr coerced-objs)))
                           (if (eq? (type-tag c-obj1)
                                    (type-tag c-obj2))
                               (apply-generic op c-obj1 c-obj2)
                               (error "Objects do not exist in the same tower hierarchy of types: APPLY-GENERIC"
                                      (list op type-tags))))))))
              (error "No method for these types: APPLY-GENERIC"
                     (list op type-tags)))))))

(define (install-integer-package)
  (define (make-integer n) (floor n))
  (define (reduce-integers n d)
    (let ((g (gcd n d)))
      (list (/ n g) (/ d g))))
  (define (tag n) (attach-tag 'integer n))
  (define (integer->rational n)
    (make-rational n 1))
  (define (integer->poly n p)
    (let ((var (variable p)))
      (make-polynomial-with-term var 0 n)))
  (put 'make 'integer
       (lambda (x) (tag (make-integer x))))
  (put 'add '(integer integer)
       (lambda (x y) (tag (+ x y))))
  (put 'sub '(integer integer)
       (lambda (x y) (tag (- x y))))
  (put 'mul '(integer integer)
       (lambda (x y) (tag (* x y))))
  (put 'div '(integer integer)
       (lambda (x y)
         (if (= (remainder x y) 0)
             (/ x y)
             (make-rational x y))))
  (put 'reduce '(integer integer)
       (lambda (x y)
         (let ((res (reduce-integers x y)))
           (list (tag (car res))
                 (tag (cadr res))))))
  (put 'equ? '(integer integer)
       (lambda (x y) (= x y)))
  (put 'greatest-common-divisor '(integer integer)
       (lambda (x y) (tag (gcd x y))))
  (put '=zero? '(integer)
       (lambda (x) (= x 0)))
  (put 'negate '(integer)
       (lambda (x) (tag (* -1 x))))
  (put 'sine '(integer)
       (lambda (x) (make-real (sin x))))
  (put 'cosine '(integer)
       (lambda (x) (make-real (cos x))))
  (put 'arctan '(integer integer)
       (lambda (x y) (make-real (atan x y))))
  (put 'square '(integer)
       (lambda (x) (tag (* x x))))
  (put 'square-root '(integer)
       (lambda (x) (make-real (sqrt x))))
  (put 'render '(integer)
       (lambda (x) (display x)))
  (put 'raise '(integer) integer->rational)
  (put 'coerce-polynomial '(integer polynomial)
       integer->poly)
  'done)
(define (make-integer n)
  ((get 'make 'integer) n))

(define (install-rational-package)
  (define (numer x) (car x))
  (define (denom x) (cdr x))
  (define (make-rat n d)
    (let ((res (reduce n d)))
      (cons (car res) (cadr res))))
  (define (add-rat x y)
    (make-rat (add (mul (numer x) (denom y))
                   (mul (numer y) (denom x)))
              (mul (denom x) (denom y))))
  (define (sub-rat x y)
    (make-rat (sub (mul (numer x) (denom y))
                   (mul (numer y) (denom x)))
              (mul (denom x) (denom y))))
  (define (mul-rat x y)
    (make-rat (mul (numer x) (numer y))
              (mul (denom x) (denom y))))
  (define (div-rat x y)
    (make-rat (mul (numer x) (denom y))
              (mul (denom x) (numer y))))
  (define (equ-rat? x y)
    (and (equ? (numer x) (numer y))
         (equ? (denom x) (denom y))))
  (define (=zero? x)
    (equ? (numer x) 0))
  (define (negate x)
    (make-rat (mul -1 (numer x))
              (denom x)))
  (define (ratio x)
    (/ (numer x) (denom x)))
  (define (tag x) (attach-tag 'rational x))
  (define (rational->real x)
    (make-real (ratio x)))
  (define (rational->integer x)
    (make-integer (floor (ratio x))))
  (define (rational->poly x p)
    (let ((var (variable p)))
      (make-polynomial-with-term var 0 x)))
  (define (render-rat x)
    (render (numer x))
    (display "/")
    (render (denom x)))
  (put 'make 'rational
    (lambda (n d) (tag (make-rat n d))))
  (put 'add '(rational rational)
       (lambda (x y) (tag (add-rat x y))))
  (put 'sub '(rational rational)
       (lambda (x y) (tag (sub-rat x y))))
  (put 'mul '(rational rational)
       (lambda (x y) (tag (mul-rat x y))))
  (put 'div '(rational rational)
       (lambda (x y) (tag (div-rat x y))))
  (put 'equ? '(rational rational) equ-rat?)
  (put '=zero? '(rational) =zero?)
  (put 'negate '(rational)
       (lambda (x) (tag (negate x))))
  (put 'sine '(rational)
       (lambda (x) (make-real (sin (ratio x)))))
  (put 'cosine '(rational)
       (lambda (x) (make-real (cos (ratio x)))))
  (put 'arctan '(rational rational)
       (lambda (x y)
         (make-real (atan (ratio x)
                          (ratio y)))))
  (put 'square '(rational)
       (lambda (x) (tag (mul-rat x x))))
  (put 'square-root '(rational)
       (lambda (x) (make-real (sqrt (ratio x)))))
  (put 'raise '(rational) rational->real)
  (put 'project '(rational) rational->integer)
  (put 'coerce-polynomial '(rational polynomial)
       rational->poly)
  (put 'render '(rational) render-rat)
  'done)
(define (make-rational n d)
  ((get 'make 'rational) n d))

(define (install-real-package)
  (define (make-real x)
    (if (pair? x)
        (let ((type (type-tag x)))
          (if (eq? type 'real)
              (contents x)
              (make-real (raise x))))
        (/ x 1.0)))
  (define (tag n) (attach-tag 'real n))
  (define (real->complex n)
    (make-complex-from-real-imag (tag n)
                                 (tag 0)))
  (define (real->rational n)
    (make-rational (round n) 1))
  (define (real->poly n p)
    (let ((var (variable p)))
      (make-polynomial-with-term var 0 n)))
  (put 'make 'real
       (lambda (x) (tag (make-real x))))
  (put 'add '(real real)
       (lambda (x y) (tag (+ x y))))
  (put 'sub '(real real)
       (lambda (x y) (tag (- x y))))
  (put 'mul '(real real)
       (lambda (x y) (tag (* x y))))
  (put 'div '(real real)
       (lambda (x y) (tag (/ x y))))
  (put 'equ? '(real real)
       (lambda (x y) (= x y)))
  (put '=zero? '(real)
       (lambda (x) (= x 0)))
  (put 'negate '(real)
       (lambda (x) (tag (* -1.0 x))))
  (put 'sine '(real)
       (lambda (x) (tag (sin x))))
  (put 'cosine '(real)
       (lambda (x) (tag (cos x))))
  (put 'arctan '(real real)
       (lambda (x y) (tag (atan x y))))
  (put 'square '(real)
       (lambda (x) (tag (* x x))))
  (put 'square-root '(real)
       (lambda (x) (tag (sqrt x))))
  (put 'render '(real)
       (lambda (x) (display x)))
  (put 'raise '(real) real->complex)
  (put 'project '(real) real->rational)
  (put 'coerce-polynomial '(real polynomial)
       real->poly)
  'done)
(define (make-real n)
  ((get 'make 'real) n))

(define (install-polar-package)
  (define (real-part z)
    (mul (magnitude z) (cosine (angle z))))
  (define (imag-part z)
    (mul (magnitude z) (sine (angle z))))
  (define (magnitude z) (car z))
  (define (angle z) (cdr z))
  (define (make-from-mag-ang r a) (cons r a))
  (define (make-from-real-imag x y)
    (cons (square-root (add (square x) (square y)))
          (arctan y x)))
  (define (tag z) (attach-tag 'polar z))
  (put 'real-part '(polar) real-part)
  (put 'imag-part '(polar) imag-part)
  (put 'magnitude '(polar) magnitude)
  (put 'angle '(polar) angle)
  (put 'make-from-mag-ang 'polar
       (lambda (r a) (tag (make-from-mag-ang r a))))
  (put 'make-from-real-imag 'polar
       (lambda (x y) (tag (make-from-real-imag x y))))
  'done)

(define (install-rectangular-package)
  (define (real-part z) (car z))
  (define (imag-part z) (cdr z))
  (define (magnitude z)
    (square-root (add (square (real-part z))
                      (square (imag-part z)))))
  (define (angle z)
    (arctan (imag-part z) (real-part z)))
  (define (make-from-real-imag x y) (cons x y))
  (define (make-from-mag-ang r a)
    (cons (mul r (cosine a))
          (mul r (sine a))))
  (define (tag z) (attach-tag 'rectangular z))
  (put 'real-part '(rectangular) real-part)
  (put 'imag-part '(rectangular) imag-part)
  (put 'magnitude '(rectangular) magnitude)
  (put 'angle '(rectangular) angle)
  (put 'make-from-mag-ang 'rectangular
       (lambda (r a) (tag (make-from-mag-ang r a))))
  (put 'make-from-real-imag 'rectangular
       (lambda (x y) (tag (make-from-real-imag x y))))
  'done)

(define (real-part z) (apply-generic 'real-part z))
(define (imag-part z) (apply-generic 'imag-part z))
(define (magnitude z) (apply-generic 'magnitude z))
(define (angle z) (apply-generic 'angle z))
(define (make-from-real-imag x y)
  ((get 'make-from-real-imag 'rectangular) x y))
(define (make-from-mag-ang r a)
  ((get 'make-from-mag-ang 'polar) r a))

(define (install-complex-package)
  (define (make-from-real-imag x y)
    ((get 'make-from-real-imag 'rectangular) x y))
  (define (make-from-mag-ang r a)
    ((get 'make-from-mag-ang 'polar) r a))
  (define (add-complex z1 z2)
    (make-from-real-imag (add (real-part z1) (real-part z2))
                         (add (imag-part z1) (imag-part z2))))
  (define (sub-complex z1 z2)
    (make-from-real-imag (sub (real-part z1) (real-part z2))
                         (sub (imag-part z1) (imag-part z2))))
  (define (mul-complex z1 z2)
    (make-from-mag-ang (mul (magnitude z1) (magnitude z2))
                       (add (angle z1) (angle z2))))
  (define (div-complex z1 z2)
    (make-from-mag-ang (div (magnitude z1) (magnitude z2))
                       (sub (angle z1) (angle z2))))
  (define (equ-complex? z1 z2)
    (and (equ? (real-part z1) (real-part z2))
         (equ? (imag-part z1) (imag-part z2))))
  (define (=zero-complex? z)
    (and (=zero? (real-part z))
         (=zero? (imag-part z))))
  (define (negate-complex z)
    (make-from-real-imag (negate (real-part z))
                         (negate (imag-part z))))
  (define (tag z) (attach-tag 'complex z))
  (define (complex->real z)
    (make-real (real-part z)))
  (define (complex->poly z p)
    (let ((var (variable p)))
      (make-polynomial-with-term var 0 z)))
  (define (render-complex z)
    (display "(")
    (render (real-part z))
    (display " + ")
    (render (imag-part z))
    (display "i)"))
  (put 'make-from-real-imag 'complex
       (lambda (x y) (tag (make-from-real-imag x y))))
  (put 'make-from-mag-ang 'complex
       (lambda (r a) (tag (make-from-mag-ang r a))))
  (put 'add '(complex complex)
       (lambda (z1 z2) (tag (add-complex z1 z2))))
  (put 'sub '(complex complex)
       (lambda (z1 z2) (tag (sub-complex z1 z2))))
  (put 'mul '(complex complex)
       (lambda (z1 z2) (tag (mul-complex z1 z2))))
  (put 'div '(complex complex)
       (lambda (z1 z2) (tag (div-complex z1 z2))))
  (put 'equ? '(complex complex) equ-complex?)
  (put '=zero? '(complex) =zero-complex?)
  (put 'negate '(complex)
       (lambda (z) (tag (negate-complex z))))
  (put 'real-part '(complex) real-part)
  (put 'imag-part '(complex) imag-part)
  (put 'magnitude '(complex) magnitude)
  (put 'angle '(complex) angle)
  (put 'project '(complex) complex->real)
  (put 'coerce-polynomial '(complex polynomial)
       complex->poly)
  (put 'render '(complex) render-complex)
  'done)
(define (make-complex-from-real-imag x y)
  ((get 'make-from-real-imag 'complex) x y))
(define (make-complex-from-mag-ang r a)
  ((get 'make-from-mag-ang 'complex) r a))

(define (install-dense-termlist-package)
  (define (adjoin-term term term-list)
    (define (adjoin coeff delta term-list)
      (cond ((<= delta 0) term-list)
            ((= delta 1)
             (adjoin coeff 0 (cons coeff term-list)))
            (else
             (adjoin coeff (- delta 1) (cons 0 term-list)))))
    (let ((highest-order (cur-order term-list)))
      (let ((delta (- (order term) highest-order)))
        (adjoin (coeff term) delta term-list))))
  (define (the-empty-termlist) '())
  (define (first-term term-list)
    (list (cur-order term-list)
          (car term-list)))
  (define (rest-terms term-list) (cdr term-list))
  (define (cur-order term-list) (- (length term-list) 1))
  (define (empty-termlist? term-list) (null? term-list))
  (define (tag L) (attach-tag 'dense L))
  (put 'make 'dense (lambda (L) (tag L)))
  (put 'adjoin-term 'dense
       (lambda (t L) (tag (adjoin-term t L))))
  (put 'the-empty-termlist 'dense
       (lambda (L) (tag (the-empty-termlist))))
  (put 'first-term '(dense) first-term)
  (put 'rest-terms '(dense)
       (lambda (L) (tag (rest-terms L))))
  (put 'empty-termlist? '(dense) empty-termlist?)
  'done)

(define (install-sparse-termlist-package)
  (define (adjoin-term term term-list)
    (if (=zero? (coeff term))
        term-list
        (cons term term-list)))
  (define (the-empty-termlist) '())
  (define (first-term term-list) (car term-list))
  (define (rest-terms term-list) (cdr term-list))
  (define (empty-termlist? term-list) (null? term-list))
  (define (tag L) (attach-tag 'sparse L))
  (put 'make 'sparse (lambda (L) (tag L)))
  (put 'adjoin-term 'sparse
       (lambda (t L) (tag (adjoin-term t L))))
  (put 'the-empty-termlist 'sparse
       (lambda (L) (tag (the-empty-termlist))))
  (put 'first-term '(sparse) first-term)
  (put 'rest-terms '(sparse)
       (lambda (L) (tag (rest-terms L))))
  (put 'empty-termlist? '(sparse) empty-termlist?)
  'done)

(define (install-termlist-package)
  (define (make-dense-termlist L)
    ((get 'make 'dense) L))
  (define (make-sparse-termlist L)
    ((get 'make 'sparse) L))
  (define (add-terms L1 L2)
    (cond ((empty-termlist? L1) L2)
          ((empty-termlist? L2) L1)
          (else
           (let ((t1 (first-term L1))
                 (t2 (first-term L2)))
             (cond ((> (order t1) (order t2))
                    (adjoin-term
                     t1 (add-terms (rest-terms L1) L2)))
                   ((> (order t2) (order t1))
                    (adjoin-term
                     t2 (add-terms L1 (rest-terms L2))))
                   (else
                    (adjoin-term
                     (make-term (order t1)
                                (add (coeff t1) (coeff t2)))
                     (add-terms (rest-terms L1)
                                (rest-terms L2)))))))))
  (define (sub-terms L1 L2)
    (add-terms L1 (negate-terms L2)))
  (define (mul-terms L1 L2)
    (if (empty-termlist? L1)
        (the-empty-termlist L1)
        (add-terms (mul-term-by-all-terms (first-term L1) L2)
                   (mul-terms (rest-terms L1) L2))))
  (define (mul-term-by-all-terms t1 L)
    (if (empty-termlist? L)
        (the-empty-termlist L)
        (let ((t2 (first-term L)))
          (adjoin-term
           (make-term (+ (order t1) (order t2))
                      (mul (coeff t1) (coeff t2)))
           (mul-term-by-all-terms t1 (rest-terms L))))))
  (define (debug-render-coeff c)
    (if (pair? c)
        (render c)
        (display c)))
  (define (debug-render-term t)
    (let ((o (order t))
          (c (coeff t)))
      (debug-render-coeff c)
      (if (> o 0)
          (begin
            (display "*x")
            (if (> o 1)
                (begin (display "^") (display o)))))))
  (define (debug-render-terms L)
    (define (iter terms first?)
      (if (empty-termlist? terms)
          (if first? (display "0"))
          (begin
            (if (not first?) (display " + "))
            (debug-render-term (first-term terms))
            (iter (rest-terms terms) #f))))
    (display "(")
    (iter L #t)
    (display ")"))
  (define (debug-display-termlist label L)
    (display label)
    (debug-render-terms L)
    (newline))
  (define (debug-display-term label t)
    (display label)
    (debug-render-term t)
    (newline))
  (define (div-terms L1 L2)
    (if (empty-termlist? L1)
        (list (the-empty-termlist L1) (the-empty-termlist L1))
        (let ((t1 (first-term L1))
              (t2 (first-term L2)))
          (if (> (order t2) (order t1))
              (list (the-empty-termlist L1) L1)
              (let ((new-c (div (coeff t1) (coeff t2)))
                    (new-o (- (order t1) (order t2))))
                (let ((rest-of-result
                       (div-terms
                        (sub-terms
                         L1 (mul-term-by-all-terms
                             (list new-o new-c) L2))
                        L2)))
                  (list
                   (adjoin-term (list new-o new-c)
                                (car rest-of-result))
                   (cadr rest-of-result))))))))
  (define (remainder-terms L1 L2)
    (cadr (div-terms L1 L2)))
  (define (scale-terms f L)
    (if (empty-termlist? L)
        (the-empty-termlist L)
        (let ((t (first-term L)))
          (adjoin-term
           (make-term (order t)
                      (mul f (coeff t)))
           (scale-terms f (rest-terms L))))))
  (define (pseudoremainder-terms L1 L2)
    (let ((t1 (first-term L1))
          (t2 (first-term L2)))
      (let ((o1 (order t1))
            (o2 (order t2))
            (c (coeff t2)))
        (let ((factor (expt c (+ 1 (- o1 o2)))))
          (remainder-terms
           (scale-terms factor L1) L2)))))
  (define (term-coeffs L)
    (if (empty-termlist? L)
        '()
        (cons (coeff (first-term L))
              (term-coeffs (rest-terms L)))))
  (define (find-terms-coeff-gcd L)
    (apply gcd (term-coeffs L)))
  (define (gcd-terms L1 L2)
    (if (=zero-terms? L2)
        (scale-terms (/ 1 (find-terms-coeff-gcd L1)) L1)
        (gcd-terms L2 (pseudoremainder-terms L1 L2))))
  (define (reduce-terms n d)
    (let ((terms-gcd (gcd-terms n d)))
      (let ((t-gcd (first-term terms-gcd))
            (tn (first-term n))
            (td (first-term d)))
        (let ((o1 (max (order tn) (order td)))
              (o2 (order t-gcd))
              (c (coeff t-gcd)))
          (let ((f (expt c (+ 1 (- o1 o2)))))
            (let ((nn-intermediate (scale-terms f n))
                  (dd-intermediate (scale-terms f d)))
              (let ((nn (car (div-terms nn-intermediate terms-gcd)))
                    (dd (car (div-terms dd-intermediate terms-gcd))))
                (let ((coeff-list
                       (append (term-coeffs nn)
                               (term-coeffs dd))))
                  (let ((reduction-factor
                         (/ 1 (apply gcd coeff-list))))
                    (let ((nn-reduced (scale-terms reduction-factor nn))
                          (dd-reduced (scale-terms reduction-factor dd)))
                    (if (< (coeff (first-term dd-reduced)) 0)
                        (list (scale-terms -1 nn-reduced)
                              (scale-terms -1 dd-reduced))
                        (list nn-reduced dd-reduced))))))))))))
  (define (nn reduction-res) (car reduction-res))
  (define (dd reduction-res) (cadr reduction-res))
  (define (=zero-terms? L)
    (if (empty-termlist? L)
        #t
        (let ((t (first-term L)))
          (if (=zero? (coeff t))
              (=zero-terms? (rest-terms L))
              #f))))
  (define (negate-terms L)
    (if (empty-termlist? L)
        (the-empty-termlist L)
        (let ((f (first-term L)))
          (adjoin-term
           (make-term (order f) (negate (coeff f)))
           (negate-terms (rest-terms L))))))
  (define (tag L) (attach-tag 'termlist L))
  (put 'make-dense-termlist 'termlist
       (lambda (L) (tag (make-dense-termlist L))))
  (put 'make-sparse-termlist 'termlist
       (lambda (L) (tag (make-sparse-termlist L))))
  (put 'adjoin-term 'termlist
       (lambda (t L) (tag (adjoin-term t L))))
  (put 'the-empty-termlist 'termlist
       (lambda (L) (tag (the-empty-termlist L))))
  (put 'first-term '(termlist) first-term)
  (put 'rest-terms '(termlist)
       (lambda (L) (tag (rest-terms L))))
  (put 'empty-termlist? '(termlist) empty-termlist?)
  (put 'add-terms 'termlist add-terms)
  (put 'sub-terms 'termlist sub-terms)
  (put 'mul-terms 'termlist mul-terms)
  (put 'div-terms 'termlist div-terms)
  (put 'negate-terms 'termlist negate-terms)
  (put '=zero-terms? 'termlist =zero-terms?)
  (put 'gcd-terms 'termlist gcd-terms)
  (put 'reduce-terms 'termlist reduce-terms)
  (put 'nn 'termlist nn)
  (put 'dd 'termlist dd)
  'done)

(define (make-dense-termlist L)  ((get 'make-dense-termlist 'termlist) L))
(define (make-sparse-termlist L) ((get 'make-sparse-termlist 'termlist) L))
(define (the-empty-termlist L)   ((get 'the-empty-termlist (type-tag L)) (contents L)))
(define (adjoin-term t L)        ((get 'adjoin-term (type-tag L)) t (contents L)))
(define (first-term L)           (apply-generic 'first-term L))
(define (rest-terms L)           (apply-generic 'rest-terms L))
(define (empty-termlist? L)      (apply-generic 'empty-termlist? L))
(define (add-terms L1 L2)        ((get 'add-terms 'termlist) L1 L2))
(define (sub-terms L1 L2)        ((get 'sub-terms 'termlist) L1 L2))
(define (mul-terms L1 L2)        ((get 'mul-terms 'termlist) L1 L2))
(define (div-terms L1 L2)        ((get 'div-terms 'termlist) L1 L2))
(define (negate-terms L)         ((get 'negate-terms 'termlist) L))
(define (=zero-terms? L)         ((get '=zero-terms? 'termlist) L))
(define (gcd-terms L1 L2)        ((get 'gcd-terms 'termlist) L1 L2))
(define (reduce-terms L1 L2)     ((get 'reduce-terms 'termlist) L1 L2))
(define (nn reduction-res)       ((get 'nn 'termlist) reduction-res))
(define (dd reduction-res)       ((get 'dd 'termlist) reduction-res))

(define (make-term order coeff) (list order coeff))
(define (order term) (car term))
(define (coeff term) (cadr term))

(define (install-polynomial-package)
  ;; internal procedures
  ;; representation of poly
  (define (make-poly variable term-list) (cons variable term-list))
  (define (variable p) (car p))
  (define (term-list p) (cdr p))
  (define (variable? x) (symbol? x))
  (define (same-variable? x y)
    (and (variable? x) (variable? y) (eq? x y)))
  (define (before-variable? v1 v2)
    (string<? (symbol->string v1) (symbol->string v2)))
  (define (poly? p)
    (eq? (type-tag p) 'polynomial))
  (define (make-canonical var terms)
    (if (empty-termlist? terms)
        (make-poly var (the-empty-termlist terms))
        (let ((t (first-term terms)))
          (add-poly
           (make-canonical var (rest-terms terms))
           (let ((c (coeff t))
                 (o (order t)))
             (if (poly? c)
                 (let ((c-poly (contents c)))
                   (let ((c-canonical
                          (make-canonical
                           (variable c-poly) (term-list c-poly))))
                     (mul-poly
                      (make-poly-with-term var o 1)
                      c-canonical)))
                 (make-poly-with-term var o c)))))))
  (define (render-poly p)
    (define (render-coeff c)
      (cond ((poly? c) (render-poly-internal (contents c)))
            ((eq? (type-tag c) 'rational)
             (display "(")
             (render c)
             (display ")"))
            (else (render c))))
    (define (render-poly-internal p)
      (let ((var (variable p))
            (tl (term-list p)))
        (display "(")
        (render-terms var tl #t)
        (display ")")))
    (define (render-terms var tl first?)
      (if (not (empty-termlist? tl))
          (let ((t (first-term tl)))
            (let ((o (order t))
                  (c (coeff t)))
              (if (not first?) (display " + "))
              (if (= o 0)
                  (render-coeff c)
                  (begin
                    (render-coeff c)
                    (display "*")
                    (display var)
                    (if (> o 1)
                        (begin (display "^") (display o)))))
              (render-terms var (rest-terms tl) #f)))))
    (render-poly-internal p))
  (define (indent depth)
    (define (loop n)
      (if (> n 0)
          (begin (display "  ") (loop (- n 1)))))
    (loop depth))
  (define (make-canonical-debug var terms)
    (display "--- begin canonicalize ") (display var) (display "-poly ---") (newline)
    (let ((result (make-canonical-debug-inner var terms 0)))
      (display "--- end canonicalize ") (display var) (display "-poly => ")
      (render-poly result) (display " ---") (newline)
      result))
  (define (make-canonical-debug-inner var terms depth)
    (if (empty-termlist? terms)
        (make-poly var (the-empty-termlist terms))
        (let ((t (first-term terms)))
          (let ((c (coeff t))
                (o (order t)))
            (indent depth)
            (display "| term: ")
            (if (poly? c)
                (begin (render-poly (contents c))
                       (display " * " ) (display var)
                       (display "^") (display o))
                (begin (display c) (display " * ")
                       (display var) (display "^") (display o)))
            (newline)
            (let ((term-result
                   (if (poly? c)
                       (let ((c-poly (contents c)))
                         (indent depth)
                         (display "|   coeff is ") (display (variable c-poly))
                         (display "-poly, canonicalizing:") (newline)
                         (let ((c-canonical
                                (make-canonical-debug-inner
                                 (variable c-poly) (term-list c-poly)
                                 (+ depth 1))))
                           (indent depth)
                           (display "|   canonical coeff: ")
                           (render-poly c-canonical) (newline)
                           (let ((result (mul-poly
                                          (make-poly-with-term var o 1)
                                          c-canonical)))
                             (indent depth)
                             (display "|   * ") (display var) (display "^") (display o)
                             (display " => ") (render-poly result) (newline)
                             result)))
                       (make-poly-with-term var o c))))
              (let ((rest-result
                     (make-canonical-debug-inner var (rest-terms terms) depth)))
                (let ((final (add-poly rest-result term-result)))
                  (indent depth)
                  (display "|= ") (render-poly final) (newline)
                  final)))))))
  (define (coerce-poly p1 p2)
    (let ((v (variable p2)))
      (let ((result (make-poly-with-term v 0 (tag p1))))
        result)))
  (define (make-poly-with-term var order coeff)
    (make-poly
     var
     (make-sparse-termlist (list (make-term order coeff)))))
  (define (add-poly p1 p2)
    (if (same-variable? (variable p1) (variable p2))
        (make-poly (variable p1)
                   (add-terms (term-list p1) (term-list p2)))
        (if (before-variable? (variable p1) (variable p2))
            (add-poly p1 (coerce-poly p2 p1))
            (add-poly (coerce-poly p1 p2) p2))))
  (define (sub-poly p1 p2)
    (add-poly p1 (negate-poly p2)))
  (define (mul-poly p1 p2)
    (if (same-variable? (variable p1) (variable p2))
        (make-poly (variable p2)
                   (mul-terms (term-list p1) (term-list p2)))
        (if (before-variable? (variable p1) (variable p2))
            (mul-poly p1 (coerce-poly p2 p1))
            (mul-poly (coerce-poly p1 p2) p2))))
  (define (div-poly p1 p2)
    (if (same-variable? (variable p1) (variable p2))
        (let ((div-res
               (div-terms (term-list p1) (term-list p2))))
          (list
           (make-poly (variable p1)
                      (car div-res))
           (make-poly (variable p1)
                      (cadr div-res))))
        (error "Polys not in same var: DIV-POLY" (list p1 p2))))
  (define (reduce-poly p1 p2)
    (if (same-variable? (variable p1) (variable p2))
        (let ((reduce-res
               (reduce-terms (term-list p1) (term-list p2))))
          (let ((nn (nn reduce-res))
                (dd (dd reduce-res)))
            (list
             (make-poly (variable p1) nn)
             (make-poly (variable p1) dd))))
        (error "Polys not in same var: REDUCE-POLY" (list p1 p2))))
  (define (gcd-poly p1 p2)
    (if (same-variable? (variable p1) (variable p2))
        (make-poly (variable p1)
                   (gcd-terms (term-list p1) (term-list p2)))
        (error "Polys not in the same var: GCD-POLY" (list p1 p2))))
  (define (=zero-poly? p) (=zero-terms? (term-list p)))
  (define (negate-poly p)
    (let ((L (term-list p))
          (var (variable p)))
      (make-poly var (negate-terms L))))
  (define (tag p) (attach-tag 'polynomial p))
  (put 'make 'polynomial
       (lambda (var term-list) (tag (make-canonical var term-list))))
  (put 'make-poly-with-term 'polynomial
       (lambda (var order coeff) (tag (make-poly-with-term var order coeff))))
  (put 'variable '(polynomial) variable)
  (put 'term-list '(polynomial) term-list)
  (put 'render '(polynomial) render-poly)
  (put 'add '(polynomial polynomial)
       (lambda (p1 p2) (tag (add-poly p1 p2))))
  (put 'sub '(polynomial polynomial)
       (lambda (p1 p2) (tag (sub-poly p1 p2))))
  (put 'mul '(polynomial polynomial)
       (lambda (p1 p2) (tag (mul-poly p1 p2))))
  (put 'div '(polynomial polynomial)
       (lambda (p1 p2)
         (let ((div-res (div-poly p1 p2)))
           (list (tag (car div-res))
                 (tag (cadr div-res))))))
  (put 'reduce '(polynomial polynomial)
       (lambda (p1 p2)
         (let ((reduce-res (reduce-poly p1 p2)))
           (list (tag (car reduce-res))
                 (tag (cadr reduce-res))))))
  (put 'greatest-common-divisor '(polynomial polynomial)
       (lambda (p1 p2) (tag (gcd-poly p1 p2))))
  (put '=zero? '(polynomial) =zero-poly?)
  (put 'negate '(polynomial)
       (lambda (p) (tag (negate-poly p))))
  'done)
(define (make-polynomial var terms)
  ((get 'make 'polynomial) var terms))
(define (make-polynomial-with-term var order coeff)
  ((get 'make-poly-with-term 'polynomial) var order coeff))
(define (variable p)  (apply-generic 'variable p))
(define (term-list p) (apply-generic 'term-list p))

(define (raise obj)     (apply-generic 'raise obj))
(define (project obj)   (apply-generic 'project obj))
(define (coerce-polynomial obj poly)
  ((get 'coerce-polynomial
        (list (type-tag obj) (type-tag poly)))
   obj poly))
(define (add x y)                     (apply-generic 'add x y))
(define (sub x y)                     (apply-generic 'sub x y))
(define (mul x y)                     (apply-generic 'mul x y))
(define (div x y)                     (apply-generic 'div x y))
(define (reduce x y)                  (apply-generic 'reduce x y))
(define (equ? x y)                    (apply-generic 'equ? x y))
(define (=zero? x)                    (apply-generic '=zero? x))
(define (negate x)                    (apply-generic 'negate x))
(define (sine x)                      (apply-generic 'sine x))
(define (cosine x)                    (apply-generic 'cosine x))
(define (arctan x y)                  (apply-generic 'arctan x y))
(define (square x)                    (apply-generic 'square x))
(define (square-root x)               (apply-generic 'square-root x))
(define (render x)                    (apply-generic 'render x))
(define (greatest-common-divisor x y) (apply-generic 'greatest-common-divisor x y))

(install-integer-package)
(install-rational-package)
(install-real-package)
(install-polar-package)
(install-rectangular-package)
(install-complex-package)
(install-dense-termlist-package)
(install-sparse-termlist-package)
(install-termlist-package)
(install-polynomial-package)

(define p1 (make-polynomial 'x (make-sparse-termlist '((2 1) (1 -2) (0 1)))))
(define p2 (make-polynomial 'x (make-sparse-termlist '((2 11) (0 7)))))
(define p3 (make-polynomial 'x (make-sparse-termlist '((1 13) (0 5)))))
(define q1 (mul p1 p2))
(define q2 (mul p1 p3))
(define q-gcd (greatest-common-divisor q1 q2))
(define reduce-res (reduce q1 q2))

(display "=== REDUCTION TEST ===") (newline)

(display "p1-poly:    ") (render p1) (newline)
(display "p2-poly:    ") (render p2) (newline)
(display "p3-poly:    ") (render p3) (newline)
(display "q1-poly:    ") (render q1) (newline)
(display "q2-poly:    ") (render q2) (newline)
(display "gcd q1 q2:  ") (render q-gcd) (newline)
(display "reduced q1: ") (render (car reduce-res)) (newline)
(display "reduced q2: ") (render (cadr reduce-res)) (newline)

(define p4 (make-polynomial 'x (make-sparse-termlist '((1 1) (0 1)))))
(define p5 (make-polynomial 'x (make-sparse-termlist '((3 1) (0 -1)))))
(define p6 (make-polynomial 'x (make-sparse-termlist '((1 1)))))
(define p7 (make-polynomial 'x (make-sparse-termlist '((2 1) (0 -1)))))
(define rf1 (make-rational p4 p5))
(define rf2 (make-rational p6 p7))
(define rf-sum (add rf1 rf2))

(display "=== EXERCISE TEST ===") (newline)

(display "p4-poly:     ")   (render p4) (newline)
(display "p5-poly:     ")   (render p5) (newline)
(display "p6-poly:     ")   (render p6) (newline)
(display "p7-poly:     ")   (render p7) (newline)
(display "rf1-poly:    ")   (render rf1) (newline)
(display "rf2-poly:    ")   (render rf2) (newline)
(display "rf-sum-poly: ")   (render rf-sum) (newline)
