#lang sicp

(define (make-cycle x)
  (set-cdr! (last-pair x) x)
  x)
(define (last-pair x)
  (if (null? (cdr x))
      x
      (last-pair (cdr x))))
(define (count-pairs x)
  (let ((distinct-pairs '()))
    (define (traverse x)
      (if (and (pair? x)
               (new-pair? x distinct-pairs))
          (begin (register-pair x)
                 (traverse (car x))
                 (traverse (cdr x)))))
    (define (register-pair x)
      (set! distinct-pairs
            (cons x distinct-pairs)))
    (define (new-pair? x pairs)
      (cond ((null? pairs) #t)
            ((eq? x (car pairs)) #f)
            (else
             (new-pair? x (cdr pairs)))))
    (define (count num pairs)
      (if (null? pairs)
          num
          (count (+ num 1) (cdr pairs))))
    (traverse x)
    (count 0 distinct-pairs)))
(define (count-and-display-pairs x)
  (let ((res (count-pairs x)))
    (display "Structure: ")
    (newline)
    (display x)
    (newline)
    (display "No. of pairs: ")
    (display res)
    (newline)))

(count-and-display-pairs (list 'a 'b 'c))
(count-and-display-pairs
 ((lambda (x)
    (set-car! x (last-pair x))
    x)
  (list 'a 'b 'c)))
(count-and-display-pairs
 ((lambda (x)
     (let ((lp (last-pair x))
           (2p (cdr x)))
       (set-car! 2p lp)
       (set-car! x 2p))
       x)
  (list 'a 'b 'c)))
(count-and-display-pairs (make-cycle (list 'a 'b 'c)))
