#lang sicp

(define (make-serializer)
  (let ((mutex (make-mutex)))
    (lambda (p)
      (define (serialized-p . args)
        (mutex 'acquire)
        (let ((val (apply p args)))
          (mutex 'release)
          val))
      serialized-p)))

(define (make-mutex)
  (let ((cell (list false)))
    (define (the-mutex m)
      (cond ((eq? m 'acquire)
             (if (set-and-test! cell)
                 (the-mutex 'acquire)))
            ((eq? m 'release) (clear! cell))))
    the-mutex))
(define (set-and-test! cell)
  (if (car cell)
      true
      (begin (set-car! cell true)
             false)))
(define (clear! cell) (set-car! cell false))

(define (make-id-generator)
  (let ((num 0))
    (define (generator m)
      (cond ((eq? m 'generate)
             (set! num (+ num 1))
             num)
            (else (error "Unknown request: MAKE-ID-GENERATOR" m))))
    generator))
(define (generate-id i) (i 'generate))

(define (make-account-and-serializer balance id-generator)
  (define (withdraw amount)
	(if (>= balance amount)
		(begin (set! balance (- balance amount))
			   balance)
		"Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (let ((balance-serializer (make-serializer))
        (id (generate-id id-generator)))
    (define (dispatch m)
      (cond ((eq? m 'withdraw) withdraw)
		    ((eq? m 'deposit) deposit)
		    ((eq? m 'balance) balance)
		    ((eq? m 'serializer) balance-serializer)
			((eq? m 'id) id)
		    (else (error "Unknown request: MAKE-ACCOUNT" m))))
	dispatch))
(define (withdraw account amount)
  (let ((s (account 'serializer))
        (w (account 'withdraw)))
    ((s w) amount)))
(define (deposit account amount)
  (let ((s (account 'serializer))
	    (d (account 'deposit)))
	((s d) amount)))
(define (exchange account1 account2)
  (let ((difference (- (account1 'balance)
					   (account2 'balance))))
	((account1 'withdraw) difference)
	((account2 'deposit) difference)))
(define (serialized-exchange a1 a2)
  (let ((s1 (a1 'serializer))
        (id1 (a1 'id))
        (s2 (a2 'serializer))
        (id2 (a2 'id)))
    (if (> id1 id2)
        ((s2 (s1 exchange)) a1 a2)
        ((s1 (s2 exchange)) a1 a2))))
