#lang sicp

(define (variable? e) (symbol? e))
(define (same-variable? v1 v2)
  (and (variable? v1)
       (variable? v2)
       (eq? v1 v2)))

(define (=number? exp num)
  (and (number? exp) (= exp num)))

(define (make-sum a1 a2)
  (cond ((=number? a1 0) a2)
        ((=number? a2 0) a1)
        ((and (number? a1) (number? a2))
         (+ a1 a2))
        (else (list a1 '+ a2))))
(define (addend s part)
  (define (part-a s) (car s))
  (define (part-b s)
    (define (try s a)
      (let ((op (cadr s))
            (term (car s)))
        (if (eq? op '+)
            (if (null? a) term (append a (list term)))
            (try (cddr s) (append a (list term op))))))
    (try s nil))
  (if (= part 1)
      (part-a s)
      (part-b s)))
(define (augend s part)
  (define (part-a s) (caddr s))
  (define (part-b s)
    (define (try s)
      (let ((op (cadr s))
            (single-term (caddr s))
            (group-term (cddr s))
            (next-term (cdddr s)))
        (if (eq? op '+)
            (if (null? next-term) single-term group-term)
            (try (cddr s)))))
    (try s))
  (if (= part 1)
      (part-a s)
      (part-b s)))
(define (sum? e part)
  (define (part-a e)
    (and (pair? e)
         (eq? (cadr e) '+)))
  (define (part-b e)
    (define (try e)
      (cond ((null? e) #f)
            ((and (pair? e)
                  (eq? (car e) '+))
             #t)
            (else (try (cddr e)))))
    (try (cdr e)))
  (if (= part 1)
      (part-a e)
      (part-b e)))

(define (make-product m1 m2)
  (cond ((or (=number? m1 0) (=number? m2 0)) 0)
        ((=number? m1 1) m2)
        ((=number? m2 1) m1)
        (else (list m1 '* m2))))
(define (multiplier p part)
  (define (part-a p) (car p))
  (define (part-b p)
    (define (try p a)
      (let ((op (cadr p))
            (term (car p)))
        (if (eq? op '*)
            (if (null? a) term (append a (list term)))
            (try (cddr p) (append a (list term op))))))
    (try p nil))
  (if (= part 1)
      (part-a p)
      (part-b p)))
(define (multiplicand p part)
  (define (part-a p) (caddr p))
  (define (part-b p)
    (define (try p)
      (let ((op (cadr p))
            (single-term (caddr p))
            (group-term (cddr p))
            (next-term (cdddr p)))
        (if (eq? op '*)
            (if (null? next-term) single-term group-term)
            (try (cddr p)))))
    (try p))
  (if (= part 1)
      (part-a p)
      (part-b p)))
(define (product? e part)
  (define (part-a e)
    (and (pair? e)
         (eq? (cadr e) '*)))
  (define (part-b e)
    (define (try e)
      (cond ((null? e) #f)
            ((and (pair? e)
                  (eq? (car e) '*))
             #t)
            (else (try (cddr e)))))
    (try (cdr e)))
  (if (= part 1)
      (part-a e)
      (part-b e)))

(define (deriv exp var part)
  (cond ((number? exp) 0)
        ((variable? exp)
         (if (same-variable? exp var) 1 0))
        ((sum? exp part)
         (make-sum (deriv (addend exp part) var part)
                   (deriv (augend exp part) var part)))
        ((product? exp part)
         (make-sum
           (make-product (multiplier exp part)
                         (deriv (multiplicand exp part) var part))
           (make-product (multiplicand exp part)
                         (deriv (multiplier exp part) var part))))
        (else (error "unknown expression type: DERIV" exp))))

; part a tests
(deriv '(x + (3 * (x + (y + 2)))) 'x 1)  ; 4
(deriv '(x * x) 'x 1)                    ; (x + x)
(deriv '(x * (x + 1)) 'x 1)              ; ((x + 1) + x)
(deriv '((x * y) + (x * 3)) 'x 1)        ; (y + 3)

; part b tests
(deriv '(x + 3 * (x + y + 2)) 'x 2)     ; 4
(deriv '(x * x) 'x 2)                   ; (x + x)
(deriv '(x * x + x) 'x 2)               ; ((x + x) + 1)
(deriv '(3 * x * y) 'x 2)               ; (3 * y)
(deriv '(x + x + x) 'x 2)               ; 3
