#lang sicp

(define *table* '())

(define (put op type item)
  (set! *table* (cons (list op type item) *table*)))
(define (get op type)
  (define (lookup key table)
    (cond ((null? table) #f)
          ((and (equal? (caar table) op)
                (equal? (cadar table) type))
           (caddar table))
          (else (lookup key (cdr table)))))
  (lookup (list op type) *table*))

(define (attach-tag type-tag contents)
  (if (eq? type-tag 'integer)
      contents
      (cons type-tag contents)))
(define (type-tag datum)
  (cond ((pair? datum) (car datum))
        ((number? datum) 'integer)
        (else (error "bad tagged datum: TYPE-TAG" datum))))
(define (contents datum)
  (cond ((pair? datum) (cdr datum))
        ((number? datum) datum)
        (else (error "bad tagged datum: CONTENTS" datum))))
(define (drop obj)
  (let ((project-proc (get 'project (list (type-tag obj)))))
    (if project-proc
        (let ((dropped-obj (project obj)))
          (let ((raise-proc (get 'raise (list (type-tag dropped-obj)))))
            (if (and raise-proc
                     (eq? (type-tag (raise dropped-obj)) (type-tag obj))
                     (equ? (raise dropped-obj) obj))
                (drop dropped-obj)
                obj)))
        obj)))
(define (apply-generic op . args)
  (define (raise-to-top obj raised-objs)
    (let ((type (type-tag obj)))
      (let ((raise-proc (get 'raise (list type))))
        (if raise-proc
            (let ((raised-obj (raise obj)))
              (raise-to-top raised-obj
                            (append raised-objs (list raised-obj))))
            raised-objs))))
  (define (raise-to-level raise-path level)
    (if (= level 0)
        (car raise-path)
        (raise-to-level (cdr raise-path) (- level 1))))
  (define (coerce obj1 obj2)
    (let ((raise-path-1 (raise-to-top obj1 (list obj1)))
          (raise-path-2 (raise-to-top obj2 (list obj2))))
      (let ((raise-length-1 (length raise-path-1))
            (raise-length-2 (length raise-path-2)))
        (let ((delta (- raise-length-1 raise-length-2)))
          (cond ((= delta 0)
                 (list obj1 obj2))
                ((< delta 0)
                 (list obj1
                       (raise-to-level raise-path-2
                                       (abs delta))))
                (else (list (raise-to-level raise-path-1 delta)
                            obj2)))))))
  (let ((type-tags (map type-tag args)))
    (let ((proc (get op type-tags)))
      (if proc
          (let ((result (apply proc (map contents args))))
            (if (memq op '(add sub mul div))
                (drop result)
                result))
          (if (= (length args) 2)
              (let ((obj1 (car args))
                    (obj2 (cadr args)))
                (let ((coerced-objs (coerce obj1 obj2)))
                  (let ((c-obj1 (car coerced-objs))
                        (c-obj2 (cadr coerced-objs)))
                    (if (eq? (type-tag c-obj1)
                             (type-tag c-obj2))
                        (apply-generic op c-obj1 c-obj2)
                        (error "Objects do not exist in the same tower hierarchy of types: APPLY-GENERIC"
                               (list op type-tags))))))
              (error "No method for these types: APPLY-GENERIC"
                     (list op type-tags)))))))

(define (install-integer-package)
  (define (make-integer n) (floor n))
  (define (tag n) (attach-tag 'integer n))
  (define (integer->rational n)
    (make-rational n 1))
  (put 'make 'integer
       (lambda (x) (tag (make-integer x))))
  (put 'add '(integer integer)
       (lambda (x y) (tag (+ x y))))
  (put 'sub '(integer integer)
       (lambda (x y) (tag (- x y))))
  (put 'mul '(integer integer)
       (lambda (x y) (tag (* x y))))
  (put 'div '(integer integer)
       (lambda (x y) (make-rational x y)))
  (put 'sine '(integer)
       (lambda (x) (make-real (sin x))))
  (put 'cosine '(integer)
       (lambda (x) (make-real (cos x))))
  (put 'arctan '(integer integer)
       (lambda (x y) (make-real (atan x y))))
  (put 'square '(integer)
       (lambda (x) (tag (* x x))))
  (put 'square-root '(integer)
       (lambda (x) (make-real (sqrt x))))
  (put 'equ? '(integer integer)
       (lambda (x y) (= x y)))
  (put 'raise '(integer) integer->rational)
  'done)
(define (make-integer n)
  ((get 'make 'integer) n))

(define (install-rational-package)
  (define (numer x) (car x))
  (define (denom x) (cdr x))
  (define (make-rat n d)
    (let ((g (gcd n d)))
      (cons (/ n g) (/ d g))))
  (define (add-rat x y)
    (make-rat (+ (* (numer x) (denom y))
                 (* (numer y) (denom x)))
              (* (denom x) (denom y))))
  (define (sub-rat x y)
    (make-rat (- (* (numer x) (denom y))
                 (* (numer y) (denom x)))
              (* (denom x) (denom y))))
  (define (mul-rat x y)
    (make-rat (* (numer x) (numer y))
              (* (denom x) (denom y))))
  (define (div-rat x y)
    (make-rat (* (numer x) (denom y))
              (* (denom x) (numer y))))
  (define (equ? x y)
    (and (= (numer x) (numer y))
         (= (denom x) (denom y))))
  (define (ratio x)
    (/ (numer x) (denom x)))
  (define (tag x) (attach-tag 'rational x))
  (define (rational->real x)
    (make-real (ratio x)))
  (define (rational->integer x)
    (make-integer (floor (ratio x))))
  (put 'make 'rational
    (lambda (n d) (tag (make-rat n d))))
  (put 'add '(rational rational)
       (lambda (x y) (tag (add-rat x y))))
  (put 'sub '(rational rational)
       (lambda (x y) (tag (sub-rat x y))))
  (put 'mul '(rational rational)
       (lambda (x y) (tag (mul-rat x y))))
  (put 'div '(rational rational)
       (lambda (x y) (tag (div-rat x y))))
  (put 'sine '(rational)
       (lambda (x) (make-real (sin (ratio x)))))
  (put 'cosine '(rational)
       (lambda (x) (make-real (cos (ratio x)))))
  (put 'arctan '(rational rational)
       (lambda (x y)
         (make-real (atan (ratio x)
                          (ratio y)))))
  (put 'square '(rational)
       (lambda (x) (tag (mul-rat x x))))
  (put 'square-root '(rational)
       (lambda (x) (make-real (sqrt (ratio x)))))
  (put 'equ? '(rational rational) equ?)
  (put 'raise '(rational) rational->real)
  (put 'project '(rational) rational->integer)
  'done)
(define (make-rational n d)
  ((get 'make 'rational) n d))

(define (install-real-package)
  (define (make-real x)
    (if (pair? x)
        (let ((type (type-tag x)))
          (if (eq? type 'real)
              (contents x)
              (make-real (raise x))))
        (/ x 1.0)))
  (define (tag n) (attach-tag 'real n))
  (define (real->complex n)
    (make-complex-from-real-imag (tag n)
                                 (tag 0)))
  (define (real->rational n)
    (make-rational (round n) 1))
  (put 'make 'real
       (lambda (x) (tag (make-real x))))
  (put 'add '(real real)
       (lambda (x y) (tag (+ x y))))
  (put 'sub '(real real)
       (lambda (x y) (tag (- x y))))
  (put 'mul '(real real)
       (lambda (x y) (tag (* x y))))
  (put 'div '(real real)
       (lambda (x y) (tag (/ x y))))
  (put 'sine '(real)
       (lambda (x) (tag (sin x))))
  (put 'cosine '(real)
       (lambda (x) (tag (cos x))))
  (put 'arctan '(real real)
       (lambda (x y) (tag (atan x y))))
  (put 'square '(real)
       (lambda (x) (tag (* x x))))
  (put 'square-root '(real)
       (lambda (x) (tag (sqrt x))))
  (put 'equ? '(real real)
       (lambda (x y) (= x y)))
  (put 'raise '(real) real->complex)
  (put 'project '(real) real->rational)
  'done)
(define (make-real n)
  ((get 'make 'real) n))

(define (install-polar-package)
  (define (real-part z)
    (mul (magnitude z) (cosine (angle z))))
  (define (imag-part z)
    (mul (magnitude z) (sine (angle z))))
  (define (magnitude z) (car z))
  (define (angle z) (cdr z))
  (define (make-from-mag-ang r a) (cons r a))
  (define (make-from-real-imag x y)
    (cons (square-root (add (square x) (square y)))
          (arctan y x)))
  (define (tag z) (attach-tag 'polar z))
  (put 'real-part '(polar) real-part)
  (put 'imag-part '(polar) imag-part)
  (put 'magnitude '(polar) magnitude)
  (put 'angle '(polar) angle)
  (put 'make-from-mag-ang 'polar
       (lambda (r a) (tag (make-from-mag-ang r a))))
  (put 'make-from-real-imag 'polar
       (lambda (x y) (tag (make-from-real-imag x y))))
  'done)

(define (install-rectangular-package)
  (define (real-part z) (car z))
  (define (imag-part z) (cdr z))
  (define (magnitude z)
    (square-root (add (square (real-part z))
                      (square (imag-part z)))))
  (define (angle z)
    (arctan (imag-part z) (real-part z)))
  (define (make-from-real-imag x y) (cons x y))
  (define (make-from-mag-ang r a)
    (cons (mul r (cosine a))
          (mul r (sine a))))
  (define (tag z) (attach-tag 'rectangular z))
  (put 'real-part '(rectangular) real-part)
  (put 'imag-part '(rectangular) imag-part)
  (put 'magnitude '(rectangular) magnitude)
  (put 'angle '(rectangular) angle)
  (put 'make-from-mag-ang 'rectangular
       (lambda (r a) (tag (make-from-mag-ang r a))))
  (put 'make-from-real-imag 'rectangular
       (lambda (x y) (tag (make-from-real-imag x y))))
  'done)

(define (real-part z) (apply-generic 'real-part z))
(define (imag-part z) (apply-generic 'imag-part z))
(define (magnitude z) (apply-generic 'magnitude z))
(define (angle z) (apply-generic 'angle z))
(define (make-from-real-imag x y)
  ((get 'make-from-real-imag 'rectangular) x y))
(define (make-from-mag-ang r a)
  ((get 'make-from-mag-ang 'polar) r a))

(define (install-complex-package)
  (define (make-from-real-imag x y)
    ((get 'make-from-real-imag 'rectangular) x y))
  (define (make-from-mag-ang r a)
    ((get 'make-from-mag-ang 'polar) r a))
  (define (add-complex z1 z2)
    (make-from-real-imag (add (real-part z1) (real-part z2))
                         (add (imag-part z1) (imag-part z2))))
  (define (sub-complex z1 z2)
    (make-from-real-imag (sub (real-part z1) (real-part z2))
                         (sub (imag-part z1) (imag-part z2))))
  (define (mul-complex z1 z2)
    (make-from-mag-ang (mul (magnitude z1) (magnitude z2))
                       (add (angle z1) (angle z2))))
  (define (div-complex z1 z2)
    (make-from-mag-ang (div (magnitude z1) (magnitude z2))
                       (sub (angle z1) (angle z2))))
  (define (equ-complex? z1 z2)
    (and (equ? (real-part z1) (real-part z2))
         (equ? (imag-part z1) (imag-part z2))))
  (define (tag z) (attach-tag 'complex z))
  (define (complex->real z)
    (make-real (real-part z)))
  (put 'make-from-real-imag 'complex
       (lambda (x y) (tag (make-from-real-imag x y))))
  (put 'make-from-mag-ang 'complex
       (lambda (r a) (tag (make-from-mag-ang r a))))
  (put 'add '(complex complex)
       (lambda (z1 z2) (tag (add-complex z1 z2))))
  (put 'sub '(complex complex)
       (lambda (z1 z2) (tag (sub-complex z1 z2))))
  (put 'mul '(complex complex)
       (lambda (z1 z2) (tag (mul-complex z1 z2))))
  (put 'div '(complex complex)
       (lambda (z1 z2) (tag (div-complex z1 z2))))
  (put 'equ? '(complex complex) equ-complex?)
  (put 'real-part '(complex) real-part)
  (put 'imag-part '(complex) imag-part)
  (put 'magnitude '(complex) magnitude)
  (put 'angle '(complex) angle)
  (put 'project '(complex) complex->real)
  'done)
(define (make-complex-from-real-imag x y)
  ((get 'make-from-real-imag 'complex) x y))
(define (make-complex-from-mag-ang r a)
  ((get 'make-from-mag-ang 'complex) r a))

(define (raise obj)
  (apply-generic 'raise obj))
(define (project obj)
  (apply-generic 'project obj))
(define (add x y)
  (apply-generic 'add x y))
(define (sub x y)
  (apply-generic 'sub x y))
(define (mul x y)
  (apply-generic 'mul x y))
(define (div x y)
  (apply-generic 'div x y))
(define (sine x)
  (apply-generic 'sine x))
(define (cosine x)
  (apply-generic 'cosine x))
(define (arctan x y)
  (apply-generic 'arctan x y))
(define (square x)
  (apply-generic 'square x))
(define (square-root x)
  (apply-generic 'square-root x))
(define (equ? x y)
  (apply-generic 'equ? x y))

(install-integer-package)
(install-rational-package)
(install-real-package)
(install-polar-package)
(install-rectangular-package)
(install-complex-package)

; test: complex with integer parts
(define c1 (make-complex-from-real-imag (make-integer 3) (make-integer 4)))
(real-part c1)  ; (integer . 3)
(imag-part c1)  ; (integer . 4)
(magnitude c1)  ; (real . 5.0)
(angle c1)

; test: complex with rational parts
(define c2 (make-complex-from-real-imag (make-rational 1 2) (make-rational 3 4)))
(real-part c2)  ; (rational 1 . 2)
(imag-part c2)  ; (rational 3 . 4)
(magnitude c2)
(angle c2)

; test: complex with real parts
(define c3 (make-complex-from-real-imag (make-real 1.5) (make-real 2.5)))
(real-part c3)  ; (real . 1.5)
(imag-part c3)  ; (real . 2.5)

; test: complex with mixed-type parts
(define c4 (make-complex-from-real-imag (make-rational 1 2) (make-integer 3)))
(real-part c4)
(imag-part c4)

; test: arithmetic on complex with generic parts
(add c1 c2)
(sub c3 c1)
(mul c1 c2)
(div c1 c2)

; test: drop with generic parts
(drop (make-complex-from-real-imag (make-integer 1) (make-integer 0)))
(drop (make-complex-from-real-imag (make-real 1.5) (make-real 0)))
(drop (make-complex-from-real-imag (make-integer 2) (make-integer 3)))
