#lang sicp

(define (make-node item) (list '() item '()))
(define (next node) (caddr node))
(define (prev node) (car node))
(define (cur node) (cadr node))
(define (set-next! node next)
  (set-car! (cddr node) next))
(define (set-prev! node prev)
  (set-car! node prev))

(define (make-deque)
  (let ((front-ptr '())
        (rear-ptr '()))
    ;; predicates
    (define (empty-deque?) (null? front-ptr))
    (define (single-node?) (eq? front-ptr rear-ptr))
    ;; selectors
    (define (front-deque)
      (if (empty-deque?)
          (error "FRONT called with an empty deque")
          (cur front-ptr)))
    (define (rear-deque)
      (if (empty-deque?)
          (error "REAR called with an empty deque")
          (cur rear-ptr)))
    ;; mutators
    (define (front-insert-deque! item)
      (let ((new-node (make-node item)))
        (cond ((empty-deque?)
               (set! front-ptr new-node)
               (set! rear-ptr new-node)
               dispatch)
              (else
               (set-prev! front-ptr new-node)
               (set-next! new-node front-ptr)
               (set! front-ptr new-node)
               dispatch))))
    (define (rear-insert-deque! item)
      (let ((new-node (make-node item)))
        (cond ((empty-deque?)
               (set! front-ptr new-node)
               (set! rear-ptr new-node)
               dispatch)
              (else
               (set-next! rear-ptr new-node)
               (set-prev! new-node rear-ptr)
               (set! rear-ptr new-node)
               dispatch))))
    (define (front-delete-deque!)
      (cond ((empty-deque?)
             (error "FRONT-DELETE! called with an empty deque"))
            ((single-node?)
             (set! front-ptr '())
             (set! rear-ptr '())
             dispatch)
            (else
             (set! front-ptr (next front-ptr))
             (set-prev! front-ptr '())
             dispatch)))
    (define (rear-delete-deque!)
      (cond ((empty-deque?)
             (error "REAR-DELETE! called with an empty deque"))
            ((single-node?)
             (set! front-ptr '())
             (set! rear-ptr '())
             dispatch)
            (else
             (set! rear-ptr (prev rear-ptr))
             (set-next! rear-ptr '())
             dispatch)))
    ;; helper print procedure
    (define (print-deque)
      (define (print items)
        (if (null? items)
            (newline)
            (begin (display (cur items))
                   (display " ")
                   (print (next items)))))
      (print front-ptr))
    (define (dispatch m)
      (cond ((eq? m 'empty-deque?) empty-deque?)
            ((eq? m 'front-deque) front-deque)
            ((eq? m 'rear-deque) rear-deque)
            ((eq? m 'front-insert-deque!) front-insert-deque!)
            ((eq? m 'rear-insert-deque!) rear-insert-deque!)
            ((eq? m 'front-delete-deque!) front-delete-deque!)
            ((eq? m 'rear-delete-deque!) rear-delete-deque!)
            ((eq? m 'print-deque) print-deque)
            (else (error "Unknown request: DEQUE" m))))
    dispatch))
(define (empty-deque? d)
  ((d 'empty-deque?)))
(define (front-deque d)
  ((d 'front-deque)))
(define (rear-deque d)
  ((d 'rear-deque)))
(define (front-insert-deque! d item)
  ((d 'front-insert-deque!) item))
(define (rear-insert-deque! d item)
  ((d 'rear-insert-deque!) item))
(define (front-delete-deque! d)
  ((d 'front-delete-deque!)))
(define (rear-delete-deque! d)
  ((d 'rear-delete-deque!)))
(define (print-deque d)
  ((d 'print-deque)))

(define d (make-deque))
(display "Initialized empty deque:            ") (print-deque d)
(display "Front-inserted a into deque:        ") (print-deque (front-insert-deque! d 'a))
(display "Rear-inserted b into deque:         ") (print-deque (rear-insert-deque! d 'b))
(display "Front-inserted c into deque:        ") (print-deque (front-insert-deque! d 'c))
(display "Rear-deleted item from deque:       ") (print-deque (rear-delete-deque! d))
(display "Front-deleted item from deque:      ") (print-deque (front-delete-deque! d))
(display "Front-deleted item from deque:      ") (print-deque (front-delete-deque! d))
(display "Rear-inserted x into deque:         ") (print-deque (rear-insert-deque! d 'x))
(display "Rear-deleted item from deque:       ") (print-deque (rear-delete-deque! d))
