#lang sicp

(define (make-account balance password)
  (let ((wrong-pwd-count 0))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                 balance)
          "Insufficient funds"))
    (define (signal-wrong-password amount) "Incorrect password")
    (define (call-the-cops amount)
      (set! wrong-pwd-count 0)
      "🚨🚨🚨 Someone's being naughty 🚨🚨🚨")
    (define (dispatch p m)
      (if (eq? p password)
          (begin (set! wrong-pwd-count 0)
                 (cond ((eq? m 'deposit) deposit)
                       ((eq? m 'withdraw) withdraw)
                       (else (error "Unknown request: MAKE-ACCOUNT" m))))
          (begin
           (set! wrong-pwd-count (+ wrong-pwd-count 1))
           (if (> wrong-pwd-count 7)
               call-the-cops
               signal-wrong-password))))
    dispatch))

(define acc1 (make-account 100 'iluvmoney))
(define acc2 (make-account 100 'iluvmoney))

(display "=== TEST: 8 consecutive incorrect attempts ===") (newline)
((acc1 'iambroke 'withdraw) 20)
((acc1 'iambroke 'withdraw) 30)
((acc1 'iambroke 'withdraw) 45)
((acc1 'iambroke 'withdraw) 2000)
((acc1 'iambroke 'withdraw) 10)
((acc1 'iambroke 'withdraw) 4)
((acc1 'iambroke 'withdraw) 10)
((acc1 'iambroke 'withdraw) 15)

(display "=== TEST: 7 consecutive incorrect attempts, followed by a correct attempt ===") (newline)
((acc2 'iambroke 'withdraw) 20)
((acc2 'iambroke 'withdraw) 30)
((acc2 'iambroke 'withdraw) 45)
((acc2 'iambroke 'withdraw) 2000)
((acc2 'iambroke 'withdraw) 10)
((acc2 'iambroke 'withdraw) 4)
((acc2 'iambroke 'withdraw) 10)
((acc2 'iluvmoney 'withdraw) 10)
((acc2 'iambroke 'withdraw) 15)
