#lang sicp

(define (make-table)
  ;; record object
  (define (make-record k v l r) (list k v l r))
  (define (record-key r) (car r))
  (define (record-val r) (cadr r))
  (define (left-branch r) (caddr r))
  (define (right-branch r) (cadddr r))
  ;; key comparison helpers
  (define (compare-keys k1 k2)
    (cond ((and (number? k1)
                (number? k2))
           (cond ((= k1 k2) '=)
                 ((> k1 k2) '>)
                 (else '<)))
          ((and (string? k1)
                (string? k2))
           (cond ((equal? k1 k2) '=)
                 ((string<? k1 k2) '<)
                 (else '>)))
          (else (error "Key types aren't supported: COMPARE-KEYS" k1 k2))))
  (define (k=? k1 k2)
    (eq? (compare-keys k1 k2) '=))
  (define (k<? k1 k2)
    (eq? (compare-keys k1 k2) '<))
  (define (k>? k1 k2)
    (eq? (compare-keys k1 k2) '>))
  ;; record operations
  (define (lookup k t)
    (cond ((null? t) #f)
          ((k<? k (record-key t))
           (lookup k (left-branch t)))
          ((k>? k (record-key t))
           (lookup k (right-branch t)))
          ((k=? k (record-key t))
           (record-val t))))
  (define (adjoin k v t)
    (cond ((null? t)
           (make-record k v '() '()))
          ((k<? k (record-key t))
           (make-record (record-key t)
                        (record-val t)
                        (adjoin k v (left-branch t))
                        (right-branch t)))
          ((k>? k (record-key t))
           (make-record (record-key t)
                        (record-val t)
                        (left-branch t)
                        (adjoin k v (right-branch t))))
          ((k=? k (record-key t))
           (make-record k
                        v
                        (left-branch t)
                        (right-branch t)))))
  ;; table data object
  (let ((table '()))
    (define (dispatch m)
      (cond ((eq? m 'lookup)
             (lambda (key)
               (lookup key table)))
            ((eq? m 'insert!)
             (lambda (key value)
               (set! table (adjoin key value table))
               'ok))
            (else (error "Unknown operation: TABLE" m))))
    dispatch))

(define (test label actual expected)
  (display label)
  (display ": ")
  (display actual)
  (display " expected ")
  (display expected)
  (display " => ")
  (display (if (equal? actual expected) 'pass 'FAIL))
  (newline))

(define num-table (make-table))
(define num-get (num-table 'lookup))
(define num-put (num-table 'insert!))

(test "missing numeric key" (num-get 5) #f)
(test "insert 5" (num-put 5 'five) 'ok)
(test "lookup 5" (num-get 5) 'five)
(test "insert 3" (num-put 3 'three) 'ok)
(test "insert 7" (num-put 7 'seven) 'ok)
(test "lookup left branch" (num-get 3) 'three)
(test "lookup right branch" (num-get 7) 'seven)
(test "update existing key" (num-put 5 'updated-five) 'ok)
(test "lookup updated key" (num-get 5) 'updated-five)
(test "missing numeric branch" (num-get 4) #f)

(define string-table (make-table))
(define string-get (string-table 'lookup))
(define string-put (string-table 'insert!))

(test "missing string key" (string-get "b") #f)
(test "insert b" (string-put "b" 2) 'ok)
(test "insert a" (string-put "a" 1) 'ok)
(test "insert c" (string-put "c" 3) 'ok)
(test "lookup string left branch" (string-get "a") 1)
(test "lookup string root" (string-get "b") 2)
(test "lookup string right branch" (string-get "c") 3)
(test "update string key" (string-put "b" '(two)) 'ok)
(test "lookup updated string key" (string-get "b") '(two))
(test "missing string branch" (string-get "d") #f)
(define table (make-table))
(define get (table 'lookup))
(define put (table 'insert!))
