#lang sicp

(define empty-marker (list '*empty*))

(define (successive-c_rs ops list)
  (cond ((null? ops) list)
        ((eq? (car ops) 'a)
         (successive-c_rs (cdr ops) (car list)))
        ((eq? (car ops) 'd)
         (successive-c_rs (cdr ops) (cdr list)))
        (else
         (error "Operation doesn't exist: SUCCESSIVE-C_RS" (car ops)))))

(define (make-table)
  (define (make-node key val left-branch right-branch children)
    (list key val left-branch right-branch children))
  (define (node-key n)
    (successive-c_rs '(a) n))
  (define (node-val n)
    (successive-c_rs '(d a) n))
  (define (left-branch n)
    (successive-c_rs '(d d a) n))
  (define (right-branch n)
    (successive-c_rs '(d d d a) n))
  (define (node-children n)
    (successive-c_rs '(d d d d a) n))
  (define (set-node-key! n k)
    (set-car! n k))
  (define (set-node-val! n v)
    (set-car! (successive-c_rs '(d) n)
              v))
  (define (set-left-branch! n b)
    (set-car! (successive-c_rs '(d d) n)
              b))
  (define (set-right-branch! n b)
    (set-car! (successive-c_rs '(d d d) n)
              b))
  (define (set-node-children! n c)
    (set-car! (successive-c_rs '(d d d d) n)
              c))
  ;; key comparison helpers
  (define (compare-keys k1 k2)
    (cond ((and (number? k1)
                (number? k2))
           (cond ((= k1 k2) '=)
                 ((> k1 k2) '>)
                 (else '<)))
          ((and (string? k1)
                (string? k2))
           (cond ((equal? k1 k2) '=)
                 ((string<? k1 k2) '<)
                 (else '>)))
          ((and (symbol? k1)
                (symbol? k2))
           (compare-keys (symbol->string k1)
                         (symbol->string k2)))
          (else (error "Key types aren't supported: COMPARE-KEYS" k1 k2))))
  (define (k=? k1 k2)
    (eq? (compare-keys k1 k2) '=))
  (define (k<? k1 k2)
    (eq? (compare-keys k1 k2) '<))
  (define (k>? k1 k2)
    (eq? (compare-keys k1 k2) '>))
  (let ((table (make-node '*table* empty-marker '() '() '())))
    (define (empty-val? t)
      (eq? (node-val t) empty-marker))
    (define (assoc k t)
      (cond ((null? t) #f)
            ((k>? k (node-key t))
             (assoc k (right-branch t)))
            ((k<? k (node-key t))
             (assoc k (left-branch t)))
            ((k=? k (node-key t)) t)))
    (define (lookup keys table)
      (if (null? keys)
          (if (empty-val? table) #f (node-val table))
          (let ((key (car keys))
                (rest-keys (cdr keys)))
            (let ((subtable
                   (assoc key (node-children table))))
              (if subtable
                  (lookup rest-keys subtable)
                  #f)))))
    (define (adjoin n t)
      (let ((v (node-val n))
            (k (node-key n)))
        (cond ((null? t) n)
              ((k>? k (node-key t))
               (make-node (node-key t)
                          (node-val t)
                          (left-branch t)
                          (adjoin n (right-branch t))
                          (node-children t)))
              ((k<? k (node-key t))
               (make-node (node-key t)
                          (node-val t)
                          (adjoin n (left-branch t))
                          (right-branch t)
                          (node-children t)))
              ; technically, this case should be unreachable
              ((k=? k (node-key t)) n))))
    (define (insert! keys value table)
      (if (null? keys)
          (set-node-val! table value)
          (let ((key (car keys))
                (rest-keys (cdr keys)))
            (let ((subtable
                   (assoc key (node-children table))))
              (if subtable
                  (insert! rest-keys value subtable)
                  (let ((new-subtable
                         (make-node key empty-marker '() '() '())))
                    (insert! rest-keys value new-subtable)
                    (set-node-children! table
                                        (adjoin new-subtable
                                                (node-children table)))))))))
    (define (dispatch m)
      (cond ((eq? m 'lookup)
             (lambda (keys)
               (lookup keys table)))
            ((eq? m 'insert!)
             (lambda (keys value)
               (insert! keys value table)
               'ok))
            (else (error "Unknown operation: TABLE" m))))
    dispatch))
(define table (make-table))
(define get (table 'lookup))
(define put (table 'insert!))

(define (test label actual expected)
  (display label)
  (display ": ")
  (display actual)
  (display " expected ")
  (display expected)
  (display " => ")
  (display (if (equal? actual expected) 'pass 'FAIL))
  (newline))

(test "missing (a)" (get '(a)) #f)
(test "put (a)" (put '(a) 1) 'ok)
(test "get (a)" (get '(a)) 1)
(test "put (a b)" (put '(a b) 2) 'ok)
(test "get (a b)" (get '(a b)) 2)
(test "get (a) still" (get '(a)) 1)
(test "update (a)" (put '(a) 3) 'ok)
(test "get updated (a)" (get '(a)) 3)
(test "get (a b) still" (get '(a b)) 2)
(test "put (a c d)" (put '(a c d) '(x y)) 'ok)
(test "get (a c d)" (get '(a c d)) '(x y))
(test "get missing prefix value (x)" (begin (put '(x y) 9) (get '(x))) #f)
(test "get (x y)" (get '(x y)) 9)
(test "get missing branch" (get '(a z)) #f)
