#lang sicp

(define (inverter input output)
  (define (invert)
    (let ((new-value (logical-not (get-signal input))))
      (after-delay inverter-delay
                   (lambda () (set-signal! output new-value)))))
  (add-action! input invert)
  'ok)
(define (and-gate a1 a2 output)
  (define (and-action-procedure)
    (let ((new-value
           (logical-and (get-signal a1)
                        (get-signal a2))))
      (after-delay and-gate-delay
                   (lambda () (set-signal! output new-value)))))
  (add-action! a1 and-action-procedure)
  (add-action! a2 and-action-procedure)
  'ok)
(define (or-gate o1 o2 output)
  (let ((i1 (make-wire))
        (i2 (make-wire))
        (a (make-wire)))
    (inverter o1 i1)
    (inverter o2 i2)
    (and-gate i1 i2 a)
    (inverter a output)
    'ok))

(define (logical-not s)
  (cond ((= s 0) 1)
	    ((= s 1) 0)
	    (else (error "Invalid signal" s))))
(define (logical-and s1 s2)
  (cond ((and (= s1 1) (= s2 1)) 1)
        ((and (= s1 0) (= s2 1)) 0)
        ((and (= s1 1) (= s2 0)) 0)
        ((and (= s1 0) (= s2 0)) 0)
        (else (error "Invalid signal" s1 s2))))
