#lang sicp

(define (front-ptr queue) (car queue))
(define (rear-ptr queue) (cdr queue))
(define (set-front-ptr! queue item)
  (set-car! queue item))
(define (set-rear-ptr! queue item)
  (set-cdr! queue item))

(define (make-queue) (cons '() '()))

(define (empty-queue? queue)
  (null? (front-ptr queue)))
(define (front-queue queue)
  (if (empty-queue? queue)
      (error "FRONT called with an empty queue" queue)
      (car (front-ptr queue))))

(define (insert-queue! queue item)
  (let ((new-pair (cons item '())))
    (cond ((empty-queue? queue)
           (set-front-ptr! queue new-pair)
           (set-rear-ptr! queue new-pair)
           queue)
          (else
           (set-cdr! (rear-ptr queue) new-pair)
           (set-rear-ptr! queue new-pair)
           queue))))
(define (delete-queue! queue)
  (cond ((empty-queue? queue)
         (error "DELETE! called with an empty queue" queue))
        (else
         (set-front-ptr! queue (cdr (front-ptr queue)))
         queue)))

(define (print-queue queue)
  (define (print items)
    (if (null? items)
        (newline)
        (begin (display (car items))
               (display " ")
               (print (cdr items)))))
  (print (front-ptr queue)))

(define q1 (make-queue))
(display "Initialized empty queue:   ") (print-queue q1)
(insert-queue! q1 'a)
(display "Inserted a into queue:     ") (print-queue q1)
(insert-queue! q1 'b)
(display "Inserted b into queue:     ") (print-queue q1)
(delete-queue! q1)
(display "Deleted item from queue:   ") (print-queue q1)
(delete-queue! q1)
(display "Deleted item from queue:   ") (print-queue q1)
