#lang sicp

(define empty-marker (list '*empty*))

(define (make-table)
  (define (make-node key)
    (list key empty-marker '()))
  (define (node-key n) (car n))
  (define (node-val n) (cadr n))
  (define (node-records n) (caddr n))
  (define (set-node-key! n k) (set-car! n k))
  (define (set-node-val! n v) (set-car! (cdr n) v))
  (define (set-node-records! n r) (set-car! (cddr n) r))
  (let ((table (make-node '*table*)))
    (define (assoc key records)
      (cond ((null? records) #f)
            ((equal? key (node-key (car records))) (car records))
            (else (assoc key (cdr records)))))
    (define (lookup keys table)
      (if (null? keys)
          (let ((val (node-val table)))
            (if (eq? val empty-marker) #f val))
          (let ((key (car keys))
                (rest-keys (cdr keys)))
            (let ((subtable
                   (assoc key (node-records table))))
              (if subtable
                  (lookup rest-keys subtable)
                  #f)))))
    (define (insert! keys value table)
      (if (null? keys)
          (set-node-val! table value)
          (let ((key (car keys))
                (rest-keys (cdr keys)))
            (let ((subtable
                   (assoc key (node-records table))))
              (if subtable
                  (insert! rest-keys value subtable)
                  (let ((new-subtable (make-node key)))
                    (insert! rest-keys value new-subtable)
                    (set-node-records! table
                                       (cons new-subtable
                                             (node-records table)))))))))
    (define (dispatch m)
      (cond ((eq? m 'lookup-proc)
             (lambda (keys)
               (lookup keys table)))
            ((eq? m 'insert-proc!)
             (lambda (keys value)
               (insert! keys value table)
               'ok))))
    dispatch))
(define table (make-table))
(define get (table 'lookup-proc))
(define put (table 'insert-proc!))

(define (test label actual expected)
  (display label)
  (display ": ")
  (display actual)
  (display " expected ")
  (display expected)
  (display " => ")
  (display (if (equal? actual expected) 'pass 'FAIL))
  (newline))

(test "missing (a)" (get '(a)) #f)
(test "put (a)" (put '(a) 1) 'ok)
(test "get (a)" (get '(a)) 1)
(test "put (a b)" (put '(a b) 2) 'ok)
(test "get (a b)" (get '(a b)) 2)
(test "get (a) still" (get '(a)) 1)
(test "update (a)" (put '(a) 3) 'ok)
(test "get updated (a)" (get '(a)) 3)
(test "get (a b) still" (get '(a b)) 2)
(test "put (a c d)" (put '(a c d) '(x y)) 'ok)
(test "get (a c d)" (get '(a c d)) '(x y))
(test "get missing prefix value (x)" (begin (put '(x y) 9) (get '(x))) #f)
(test "get (x y)" (get '(x y)) 9)
(test "get missing branch" (get '(a z)) #f)
