#lang sicp

(define (make-mutex)
  (let ((cell (list false)))
    (define (the-mutex m)
      (cond ((eq? m 'acquire)
             (if (test-and-set! cell)
                 (the-mutex 'acquire)))
            ((eq? m 'release) (clear! cell))))
    the-mutex))
(define (clear! cell) (set-car! cell false))
(define (test-and-set! cell)
  (if (car cell)
      true
      (begin (set-car! cell true)
             false)))

(define (make-semaphore-incorrect n)
  (define (construct cells n)
    (if (= n 0)
        cells
        (construct (cons (make-mutex) cells)
                   (- n 1))))
  (define (test-and-set! cells)
    (cond ((null? cells) true)
          ((not (car (car cells)))
           (begin (set-car! (car cells) true)
                  false))
          (else
           (test-and-set! (cdr cells)))))
  (define (clear! cells)
    (cond ((null? cells) 'all-clear)
          ((car (car cells))
           (set-car! (car cells) false))
          (else (clear! (cdr cells)))))
  (let ((cells (construct '() n)))
    (define (the-semaphore m)
      (cond ((eq? m 'acquire)
             (if (test-and-set! cells)
                 (the-semaphore 'acquire)))
            ((eq? m 'release) (clear! cells))))
    the-semaphore))

(define (make-semaphore-a n)
  (let ((locks n)
        (mutex (make-mutex)))
    (define (acquire-lock)
      (mutex 'acquire)
      (if (> locks 0)
          (begin
           (set! locks (- locks 1))
           (mutex 'release))
          (begin
           (mutex 'release)
           (acquire-lock))))
    (define (release-lock)
      (mutex 'acquire)
      (set! locks (+ locks 1))
      (mutex 'release))
    (define (the-semaphore m)
      (cond ((eq? m 'acquire) (acquire-lock))
            ((eq? m 'release) (release-lock))))
    the-semaphore))

(define (make-semaphore-b n)
  (let ((locks n)
        (cell (list false)))
    (define (acquire-lock)
      (if (test-and-set! cell)
          (acquire-lock)
          (if (> locks 0)
              (begin (set! locks (- locks 1))
                     (clear! cell))
              (begin (clear! cell)
                     (acquire-lock)))))
    (define (release-lock)
      (if (test-and-set! cell)
          (release-lock)
          (begin (set! locks (+ locks 1))
                 (clear! cell))))
    (define (the-semaphore m)
      (cond ((eq? m 'acquire) (acquire-lock))
            ((eq? m 'release) (release-lock))))
    the-semaphore))
