#lang sicp

(define *table* '())

(define (put op type item)
  (set! *table* (cons (list op type item) *table*)))

(define (get op type)
  (define (lookup key table)
    (cond ((null? table) #f)
          ((and (equal? (caar table) op)
                (equal? (cadar table) type))
           (caddar table))
          (else (lookup key (cdr table)))))
  (lookup (list op type) *table*))

(define (attach-tag type-tag contents)
  (if (number? contents)
      contents
      (cons type-tag contents)))
(define (type-tag datum)
  (cond ((pair? datum) (car datum))
        ((number? datum) 'scheme-number)
        (else (error "bad tagged datum: TYPE-TAG" datum))))
(define (contents datum)
  (cond ((pair? datum) (cdr datum))
        ((number? datum) datum)
        (else (error "bad tagged datum: CONTENTS" datum))))

(define (apply-generic op . args)
  (let ((type-tags (map type-tag args)))
    (let ((proc (get op type-tags)))
      (if proc
          (apply proc (map contents args))
          (error "No method for these types: APPLY-GENERIC" (list op type-tags))))))

(define (install-scheme-number-package)
  (define (tag x) (attach-tag 'scheme-number x))
  (put 'add '(scheme-number scheme-number)
       (lambda (x y) (tag (+ x y))))
  (put 'sub '(scheme-number scheme-number)
       (lambda (x y) (tag (- x y))))
  (put 'mul '(scheme-number scheme-number)
       (lambda (x y) (tag (* x y))))
  (put 'div '(scheme-number scheme-number)
       (lambda (x y) (tag (/ x y))))
  (put 'make 'scheme-number (lambda (x) (tag x)))
  'done)
(define (make-scheme-number n)
  ((get 'make 'scheme-number) n))

(define (add n1 n2)
  (apply-generic 'add n1 n2))
(define (sub n1 n2)
  (apply-generic 'sub n1 n2))
(define (mul n1 n2)
  (apply-generic 'mul n1 n2))
(define (div n1 n2)
  (apply-generic 'div n1 n2))

(install-scheme-number-package)

(add (make-scheme-number 4)
     (make-scheme-number 5))
(sub (make-scheme-number 10)
     (make-scheme-number 3))
(mul (make-scheme-number 6)
     (make-scheme-number 7))
(div (make-scheme-number 20)
     (make-scheme-number 4))
