#lang sicp

(define *table* '())

(define (put op type item)
  (set! *table* (cons (list op type item) *table*)))
(define (get op type)
  (define (lookup key table)
    (cond ((null? table) #f)
          ((and (equal? (caar table) op)
                (equal? (cadar table) type))
           (caddar table))
          (else (lookup key (cdr table)))))
  (lookup (list op type) *table*))

(define (attach-tag type-tag contents)
  (if (eq? type-tag 'integer)
      contents
      (cons type-tag contents)))
(define (type-tag datum)
  (cond ((pair? datum) (car datum))
        ((number? datum) 'integer)
        (else (error "bad tagged datum: TYPE-TAG" datum))))
(define (contents datum)
  (cond ((pair? datum) (cdr datum))
        ((number? datum) datum)
        (else (error "bad tagged datum: CONTENTS" datum))))
(define (drop obj)
  (let ((project-proc (get 'project (list (type-tag obj)))))
    (if project-proc
        (let ((dropped-obj (project obj)))
          (let ((raise-proc (get 'raise (list (type-tag dropped-obj)))))
            (if (and raise-proc
                     (eq? (type-tag (raise dropped-obj)) (type-tag obj))
                     (equ? (raise dropped-obj) obj))
                (drop dropped-obj)
                obj)))
        obj)))
(define (apply-generic op . args)
  (define (raise-to-top obj raised-objs)
    (let ((type (type-tag obj)))
      (let ((raise-proc (get 'raise (list type))))
        (if raise-proc
            (let ((raised-obj (raise obj)))
              (raise-to-top raised-obj
                            (append raised-objs (list raised-obj))))
            raised-objs))))
  (define (raise-to-level raise-path level)
    (if (= level 0)
        (car raise-path)
        (raise-to-level (cdr raise-path) (- level 1))))
  (define (coerce obj1 obj2)
    (let ((raise-path-1 (raise-to-top obj1 (list obj1)))
          (raise-path-2 (raise-to-top obj2 (list obj2))))
      (let ((raise-length-1 (length raise-path-1))
            (raise-length-2 (length raise-path-2)))
        (let ((delta (- raise-length-1 raise-length-2)))
          (cond ((= delta 0)
                 (list obj1 obj2))
                ((< delta 0)
                 (list obj1
                       (raise-to-level raise-path-2
                                       (abs delta))))
                (else (list (raise-to-level raise-path-1 delta)
                            obj2)))))))
  (let ((type-tags (map type-tag args)))
    (let ((proc (get op type-tags)))
      (if proc
          (let ((result (apply proc (map contents args))))
            (if (memq op '(add sub mul div))
                (drop result)
                result))
          (if (= (length args) 2)
              (let ((obj1 (car args))
                    (obj2 (cadr args)))
                (let ((coerced-objs (coerce obj1 obj2)))
                  (let ((c-obj1 (car coerced-objs))
                        (c-obj2 (cadr coerced-objs)))
                    (if (eq? (type-tag c-obj1)
                             (type-tag c-obj2))
                        (apply-generic op c-obj1 c-obj2)
                        (error "Objects do not exist in the same tower hierarchy of types: APPLY-GENERIC"
                               (list op type-tags))))))
              (error "No method for these types: APPLY-GENERIC"
                     (list op type-tags)))))))

(define (install-integer-package)
  (define (make-integer n) (floor n))
  (define (tag n) (attach-tag 'integer n))
  (define (integer->rational n)
    (make-rational n 1))
  (put 'make 'integer
       (lambda (x) (tag (make-integer x))))
  (put 'add '(integer integer)
       (lambda (x y) (tag (+ x y))))
  (put 'sub '(integer integer)
       (lambda (x y) (tag (- x y))))
  (put 'mul '(integer integer)
       (lambda (x y) (tag (* x y))))
  (put 'div '(integer integer)
       (lambda (x y) (make-rational x y)))
  (put 'equ? '(integer integer)
       (lambda (x y) (= x y)))
  (put '=zero? '(integer)
       (lambda (x) (= x 0)))
  (put 'negate '(integer)
       (lambda (x) (tag (* -1 x))))
  (put 'sine '(integer)
       (lambda (x) (make-real (sin x))))
  (put 'cosine '(integer)
       (lambda (x) (make-real (cos x))))
  (put 'arctan '(integer integer)
       (lambda (x y) (make-real (atan x y))))
  (put 'square '(integer)
       (lambda (x) (tag (* x x))))
  (put 'square-root '(integer)
       (lambda (x) (make-real (sqrt x))))
  (put 'raise '(integer) integer->rational)
  'done)
(define (make-integer n)
  ((get 'make 'integer) n))

(define (install-rational-package)
  (define (numer x) (car x))
  (define (denom x) (cdr x))
  (define (make-rat n d)
    (let ((g (gcd n d)))
      (cons (/ n g) (/ d g))))
  (define (add-rat x y)
    (make-rat (+ (* (numer x) (denom y))
                 (* (numer y) (denom x)))
              (* (denom x) (denom y))))
  (define (sub-rat x y)
    (make-rat (- (* (numer x) (denom y))
                 (* (numer y) (denom x)))
              (* (denom x) (denom y))))
  (define (mul-rat x y)
    (make-rat (* (numer x) (numer y))
              (* (denom x) (denom y))))
  (define (div-rat x y)
    (make-rat (* (numer x) (denom y))
              (* (denom x) (numer y))))
  (define (equ? x y)
    (and (= (numer x) (numer y))
         (= (denom x) (denom y))))
  (define (=zero? x)
    (= (numer x) 0))
  (define (negate x)
    (make-rat (* -1 (numer x))
              (denom x)))
  (define (ratio x)
    (/ (numer x) (denom x)))
  (define (tag x) (attach-tag 'rational x))
  (define (rational->real x)
    (make-real (ratio x)))
  (define (rational->integer x)
    (make-integer (floor (ratio x))))
  (put 'make 'rational
    (lambda (n d) (tag (make-rat n d))))
  (put 'add '(rational rational)
       (lambda (x y) (tag (add-rat x y))))
  (put 'sub '(rational rational)
       (lambda (x y) (tag (sub-rat x y))))
  (put 'mul '(rational rational)
       (lambda (x y) (tag (mul-rat x y))))
  (put 'div '(rational rational)
       (lambda (x y) (tag (div-rat x y))))
  (put 'equ? '(rational rational) equ?)
  (put '=zero? '(rational) =zero?)
  (put 'negate '(rational)
       (lambda (x) (tag (negate x))))
  (put 'sine '(rational)
       (lambda (x) (make-real (sin (ratio x)))))
  (put 'cosine '(rational)
       (lambda (x) (make-real (cos (ratio x)))))
  (put 'arctan '(rational rational)
       (lambda (x y)
         (make-real (atan (ratio x)
                          (ratio y)))))
  (put 'square '(rational)
       (lambda (x) (tag (mul-rat x x))))
  (put 'square-root '(rational)
       (lambda (x) (make-real (sqrt (ratio x)))))
  (put 'raise '(rational) rational->real)
  (put 'project '(rational) rational->integer)
  'done)
(define (make-rational n d)
  ((get 'make 'rational) n d))

(define (install-real-package)
  (define (make-real x)
    (if (pair? x)
        (let ((type (type-tag x)))
          (if (eq? type 'real)
              (contents x)
              (make-real (raise x))))
        (/ x 1.0)))
  (define (tag n) (attach-tag 'real n))
  (define (real->complex n)
    (make-complex-from-real-imag (tag n)
                                 (tag 0)))
  (define (real->rational n)
    (make-rational (round n) 1))
  (put 'make 'real
       (lambda (x) (tag (make-real x))))
  (put 'add '(real real)
       (lambda (x y) (tag (+ x y))))
  (put 'sub '(real real)
       (lambda (x y) (tag (- x y))))
  (put 'mul '(real real)
       (lambda (x y) (tag (* x y))))
  (put 'div '(real real)
       (lambda (x y) (tag (/ x y))))
  (put 'equ? '(real real)
       (lambda (x y) (= x y)))
  (put '=zero? '(real)
       (lambda (x) (= x 0)))
  (put 'negate '(real)
       (lambda (x) (tag (* -1.0 x))))
  (put 'sine '(real)
       (lambda (x) (tag (sin x))))
  (put 'cosine '(real)
       (lambda (x) (tag (cos x))))
  (put 'arctan '(real real)
       (lambda (x y) (tag (atan x y))))
  (put 'square '(real)
       (lambda (x) (tag (* x x))))
  (put 'square-root '(real)
       (lambda (x) (tag (sqrt x))))
  (put 'raise '(real) real->complex)
  (put 'project '(real) real->rational)
  'done)
(define (make-real n)
  ((get 'make 'real) n))

(define (install-polar-package)
  (define (real-part z)
    (mul (magnitude z) (cosine (angle z))))
  (define (imag-part z)
    (mul (magnitude z) (sine (angle z))))
  (define (magnitude z) (car z))
  (define (angle z) (cdr z))
  (define (make-from-mag-ang r a) (cons r a))
  (define (make-from-real-imag x y)
    (cons (square-root (add (square x) (square y)))
          (arctan y x)))
  (define (tag z) (attach-tag 'polar z))
  (put 'real-part '(polar) real-part)
  (put 'imag-part '(polar) imag-part)
  (put 'magnitude '(polar) magnitude)
  (put 'angle '(polar) angle)
  (put 'make-from-mag-ang 'polar
       (lambda (r a) (tag (make-from-mag-ang r a))))
  (put 'make-from-real-imag 'polar
       (lambda (x y) (tag (make-from-real-imag x y))))
  'done)

(define (install-rectangular-package)
  (define (real-part z) (car z))
  (define (imag-part z) (cdr z))
  (define (magnitude z)
    (square-root (add (square (real-part z))
                      (square (imag-part z)))))
  (define (angle z)
    (arctan (imag-part z) (real-part z)))
  (define (make-from-real-imag x y) (cons x y))
  (define (make-from-mag-ang r a)
    (cons (mul r (cosine a))
          (mul r (sine a))))
  (define (tag z) (attach-tag 'rectangular z))
  (put 'real-part '(rectangular) real-part)
  (put 'imag-part '(rectangular) imag-part)
  (put 'magnitude '(rectangular) magnitude)
  (put 'angle '(rectangular) angle)
  (put 'make-from-mag-ang 'rectangular
       (lambda (r a) (tag (make-from-mag-ang r a))))
  (put 'make-from-real-imag 'rectangular
       (lambda (x y) (tag (make-from-real-imag x y))))
  'done)

(define (real-part z) (apply-generic 'real-part z))
(define (imag-part z) (apply-generic 'imag-part z))
(define (magnitude z) (apply-generic 'magnitude z))
(define (angle z) (apply-generic 'angle z))
(define (make-from-real-imag x y)
  ((get 'make-from-real-imag 'rectangular) x y))
(define (make-from-mag-ang r a)
  ((get 'make-from-mag-ang 'polar) r a))

(define (install-complex-package)
  (define (make-from-real-imag x y)
    ((get 'make-from-real-imag 'rectangular) x y))
  (define (make-from-mag-ang r a)
    ((get 'make-from-mag-ang 'polar) r a))
  (define (add-complex z1 z2)
    (make-from-real-imag (add (real-part z1) (real-part z2))
                         (add (imag-part z1) (imag-part z2))))
  (define (sub-complex z1 z2)
    (make-from-real-imag (sub (real-part z1) (real-part z2))
                         (sub (imag-part z1) (imag-part z2))))
  (define (mul-complex z1 z2)
    (make-from-mag-ang (mul (magnitude z1) (magnitude z2))
                       (add (angle z1) (angle z2))))
  (define (div-complex z1 z2)
    (make-from-mag-ang (div (magnitude z1) (magnitude z2))
                       (sub (angle z1) (angle z2))))
  (define (equ-complex? z1 z2)
    (and (equ? (real-part z1) (real-part z2))
         (equ? (imag-part z1) (imag-part z2))))
  (define (=zero-complex? z)
    (and (=zero? (real-part z))
         (=zero? (imag-part z))))
  (define (negate-complex z)
    (make-from-real-imag (negate (real-part z))
                         (negate (imag-part z))))
  (define (tag z) (attach-tag 'complex z))
  (define (complex->real z)
    (make-real (real-part z)))
  (put 'make-from-real-imag 'complex
       (lambda (x y) (tag (make-from-real-imag x y))))
  (put 'make-from-mag-ang 'complex
       (lambda (r a) (tag (make-from-mag-ang r a))))
  (put 'add '(complex complex)
       (lambda (z1 z2) (tag (add-complex z1 z2))))
  (put 'sub '(complex complex)
       (lambda (z1 z2) (tag (sub-complex z1 z2))))
  (put 'mul '(complex complex)
       (lambda (z1 z2) (tag (mul-complex z1 z2))))
  (put 'div '(complex complex)
       (lambda (z1 z2) (tag (div-complex z1 z2))))
  (put 'equ? '(complex complex) equ-complex?)
  (put '=zero? '(complex) =zero-complex?)
  (put 'negate '(complex)
       (lambda (z) (tag (negate-complex z))))
  (put 'real-part '(complex) real-part)
  (put 'imag-part '(complex) imag-part)
  (put 'magnitude '(complex) magnitude)
  (put 'angle '(complex) angle)
  (put 'project '(complex) complex->real)
  'done)
(define (make-complex-from-real-imag x y)
  ((get 'make-from-real-imag 'complex) x y))
(define (make-complex-from-mag-ang r a)
  ((get 'make-from-mag-ang 'complex) r a))

(define (install-polynomial-package)
  ;; internal procedures
  ;; representation of poly
  (define (make-poly variable term-list) (cons variable term-list))
  (define (variable p) (car p))
  (define (term-list p) (cdr p))
  (define (variable? x) (symbol? x))
  (define (same-variable? x y)
    (and (variable? x) (variable? y) (eq? x y)))
  ;; representation of terms and term lists
  (define (adjoin-term term term-list)
    (if (=zero? (coeff term))
        term-list
        (cons term term-list)))
  (define (the-empty-termlist) '())
  (define (first-term term-list) (car term-list))
  (define (rest-terms term-list) (cdr term-list))
  (define (empty-termlist? term-list) (null? term-list))
  (define (make-term order coeff) (list order coeff))
  (define (order term) (car term))
  (define (coeff term) (cadr term))
  (define (add-poly p1 p2)
    (if (same-variable? (variable p1) (variable p2))
        (make-poly (variable p1)
                   (add-terms (term-list p1) (term-list p2)))
        (error "Polys not in same var: ADD-POLY" (list p1 p2))))
  (define (add-terms L1 L2)
    (cond ((empty-termlist? L1) L2)
          ((empty-termlist? L2) L1)
          (else
           (let ((t1 (first-term L1))
                 (t2 (first-term L2)))
             (cond ((> (order t1) (order t2))
                    (adjoin-term
                     t1 (add-terms (rest-terms L1) L2)))
                   ((> (order t2) (order t1))
                    (adjoin-term
                     t2 (add-terms L1 (rest-terms L2))))
                   (else
                    (adjoin-term
                     (make-term (order t1)
                                (add (coeff t1) (coeff t2)))
                     (add-terms (rest-terms L1)
                                (rest-terms L2)))))))))
  (define (sub-poly p1 p2)
    (add-poly p1 (negate-poly p2)))
  (define (mul-poly p1 p2)
    (if (same-variable? (variable p1) (variable p2))
        (make-poly (variable p2)
                   (mul-terms (term-list p1) (term-list p2)))
        (error "Polys not in same var: MUL-POLY" (list p1 p2))))
  (define (mul-terms L1 L2)
    (if (empty-termlist? L1)
        (the-empty-termlist)
        (add-terms (mul-term-by-all-terms (first-term L1) L2)
                   (mul-terms (rest-terms L1) L2))))
  (define (mul-term-by-all-terms t1 L)
    (if (empty-termlist? L)
        (the-empty-termlist)
        (let ((t2 (first-term L)))
          (adjoin-term
           (make-term (+ (order t1) (order t2))
                      (mul (coeff t1) (coeff t2)))
           (mul-term-by-all-terms t1 (rest-terms L))))))
  (define (=zero-poly? p) (=zero-terms? (term-list p)))
  (define (=zero-terms? L)
    (if (empty-termlist? L)
        #t
        (let ((t (first-term L)))
          (if (=zero? (coeff t))
              (=zero-terms? (rest-terms L))
              #f))))
  (define (negate-poly p)
    (let ((L (term-list p))
          (var (variable p)))
      (make-poly var
                 (map negate-term L))))
  (define (negate-term t)
    (make-term (order t) (negate (coeff t))))
  (define (tag p) (attach-tag 'polynomial p))
  (put 'make 'polynomial
       (lambda (var term-list) (tag (make-poly var term-list))))
  (put 'make-term 'polynomial make-term)
  (put 'add '(polynomial polynomial)
       (lambda (p1 p2) (tag (add-poly p1 p2))))
  (put 'sub '(polynomial polynomial)
       (lambda (p1 p2) (tag (sub-poly p1 p2))))
  (put 'mul '(polynomial polynomial)
       (lambda (p1 p2) (tag (mul-poly p1 p2))))
  (put '=zero? '(polynomial) =zero-poly?)
  (put 'negate '(polynomial)
       (lambda (p) (tag (negate-poly p))))
  'done)
(define (make-polynomial var terms)
  ((get 'make 'polynomial) var terms))
(define (make-term order coeff)
  ((get 'make-term 'polynomial) order coeff))

(define (raise obj)     (apply-generic 'raise obj))
(define (project obj)   (apply-generic 'project obj))
(define (add x y)       (apply-generic 'add x y))
(define (sub x y)       (apply-generic 'sub x y))
(define (mul x y)       (apply-generic 'mul x y))
(define (div x y)       (apply-generic 'div x y))
(define (equ? x y)      (apply-generic 'equ? x y))
(define (=zero? x)      (apply-generic '=zero? x))
(define (negate x)      (apply-generic 'negate x))
(define (sine x)        (apply-generic 'sine x))
(define (cosine x)      (apply-generic 'cosine x))
(define (arctan x y)    (apply-generic 'arctan x y))
(define (square x)      (apply-generic 'square x))
(define (square-root x) (apply-generic 'square-root x))

(install-integer-package)
(install-rational-package)
(install-real-package)
(install-polar-package)
(install-rectangular-package)
(install-complex-package)
(install-polynomial-package)

;; tests for negate and sub
(define p1 (make-polynomial 'x (list (make-term 2 3) (make-term 1 2) (make-term 0 1))))  ; 3x^2 + 2x + 1
(define p2 (make-polynomial 'x (list (make-term 2 1) (make-term 1 1) (make-term 0 1))))  ; x^2 + x + 1

(display "negate 3x^2+2x+1:   ")  (display (negate p1))           (newline)  ; -3x^2 - 2x - 1
(display "sub p1 - p2:        ")  (display (sub p1 p2))           (newline)  ; 2x^2 + x
(display "sub p1 - p1:        ")  (display (sub p1 p1))           (newline)  ; 0 (empty poly)
(display "=zero? (p1 - p1):   ")  (display (=zero? (sub p1 p1)))  (newline)  ; #t

;; nested polynomial subtraction
(define pn1 (make-polynomial 'x (list (make-term 1 (make-polynomial 'y (list (make-term 1 3)))))))  ; 3y * x
(define pn2 (make-polynomial 'x (list (make-term 1 (make-polynomial 'y (list (make-term 1 1)))))))  ; y * x
(display "nested sub pn1-pn2: ") (display (sub pn1 pn2))          (newline)  ; 2y * x
(display "=zero? nested sub:  ") (display (=zero? (sub pn1 pn1))) (newline)  ; #t
